- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/troubleshooting.md
Adds standard issue templates required by New Relic Product.
> Add issue templates.

- newrelic/api/cat_header_mixin.py
This issue happened with Tornado. Within async POST handler, if we finish the request with self.finish() before using AsyncHttp client for making a http request, the transaction is 'exited' with settings set to None. But we land up in generate_request_headers with 'transaction' not set to None but transaction.settings None, leading to exception:
```
Traceback (most recent call last):
File "/home/ketan/repo/iot/newrelic/iot-data-manager/services/common/asynchttp.py", line 24, in fetch
async_http_response = await http_client.fetch(url)
File "/home/ketan/.local/lib/python3.6/site-packages/newrelic/hooks/framework_tornado.py", line 284, in wrap_httpclient_fetch
outgoing_headers = trace.generate_request_headers(current_transaction())
File …
```
> Check for None before accessing transaction settings

- newrelic/core/agent.py
threading.Thread.isAlive() is removed in python3.9
> The isAlive() method of threading.Thread has been removed. It was deprecated since Python 3.8. Use is_alive() instead. (Contributed by Dong-hee Na in bpo-37804.)
https://docs.python.org/3.9/whatsnew/3.9.html#removed
> Use is_alive in place of deprecated isAlive

- newrelic/api/import_hook.py
- tests/agent_unittests/test_import_hook.py
For Python >=3.4, using find_loader is deprecated, and importing it
generates a DeprecationWarning. Mirroring wrapt's implementation of a
similar construct in its importer.py (on which this code seems modeled),
we can try to use the new find_spec first,  then the old python 2.7
fallback, as before. Since the newrelic python agent only supports 2.7+
and 3.5+, there is no need to keep support for the deprecated
find_loader at all.
The immediate result of this change is that one less DeprecationWarning
is fired at runtime when using the newrelic python agent. …
> Fix DeprecationWarning in import_hook

- .github/workflows/tests.yml
* Adds caching of .tox directories and pip cache directories across test runs.
* Consolidates runners to have all versions of python installed.
* Runs all tox environments in parallel for each test directory.
N/A
This update affects all tests currently running.
Sidekick: @a-feld
> Adding Caching to GHA Testing

- .github/workflows/tests.yml
- tests/framework_fastapi/_target_application.py
- tests/framework_fastapi/conftest.py
- tests/framework_fastapi/test_application.py
- tests/framework_fastapi/tox.ini
* Import fastapi tests to public repo.
* Consolidates fastapi tests to run only with C extensions.
> PYTHON-3826: Adding fastapi tests

- .github/workflows/tests.yml
- tests/application_celery/conftest.py
- tests/application_celery/tasks.py
- tests/application_celery/test_celery.py
- tests/application_celery/test_celery_max_tasks_per_child.py
- tests/application_celery/tox.ini
- tests/testing_support/validators/validate_function_called.py
* Ports internal test suite to public repo.
* Reduces testing matrix to remove C extension based testing.
PYTHON-3777
> PYTHON-3777 Celery Tests

- .github/workflows/tests.yml
- tests/framework_tornado/_target_application.py
- tests/framework_tornado/conftest.py
- tests/framework_tornado/test_custom_handler.py
- tests/framework_tornado/test_externals.py
- tests/framework_tornado/test_inbound_cat.py
- tests/framework_tornado/test_server.py
- tests/framework_tornado/tox.ini
- tests/testing_support/external_fixtures.py
- tests/testing_support/validators/validate_transaction_count.py
* Ports tornado tests to public repo
* Cleans up some logic and language
* Removes unsupported py35 from tornado master.
PYTHON-3832
> PYTHON-3832 Tornado Tests

- .github/workflows/tests.yml
- tests/framework_aiohttp/_target_application.py
- tests/framework_aiohttp/conftest.py
- tests/framework_aiohttp/test_client.py
- tests/framework_aiohttp/test_client_async_await.py
- tests/framework_aiohttp/test_client_cat.py
- tests/framework_aiohttp/test_externals.py
- tests/framework_aiohttp/test_middleware.py
- tests/framework_aiohttp/test_server.py
- tests/framework_aiohttp/test_server_cat.py
- tests/framework_aiohttp/test_ws.py
- tests/framework_aiohttp/tox.ini
- tests/framework_tornado/test_externals.py
- tests/testing_support/external_fixtures.py
- tests/testing_support/mock_external_http_server.py
* Porting aiohttp tests from internal repo.
* Cleans up test language.
* Upgrades `MockExternalHttpServer` (and subclasses) to bind to a random open port when unspecified, with retrying.
* Tweak tornado tests using above class to utilize new functionality.
PYTHON-3821
> PYTHON-3821 aiohttp Tests

- .github/workflows/tests.yml
- tests/datastore_bmemcached/conftest.py
- tests/datastore_bmemcached/test_memcache.py
- tests/datastore_bmemcached/tox.ini
- tests/testing_support/db_settings.py
* Added memcached based testing workflow
* Imported bmemcached tests from internal repo
* Overhauled memcached settings from tddium
* Upgraded memcached tested version to latest
PYTHON-3788
> PYTHON-3788 bmemcached Tests

- .github/workflows/tests.yml
- tests/datastore_memcache/conftest.py
- tests/datastore_memcache/test_all_methods_wrapped.py
- tests/datastore_memcache/test_memcache.py
- tests/datastore_memcache/test_multiple_dbs.py
- tests/datastore_memcache/test_span_event.py
- tests/datastore_memcache/tox.ini
- tests/testing_support/db_settings.py
* Added memcache tests from internal repo.
* Cleaned up namespacing to use `os.getpid()`
* Reduced testing matrix
PYTHON-3790
> PYTHON-3790 memcache Tests

- .github/workflows/tests.yml
- tests/datastore_pymemcache/conftest.py
- tests/datastore_pymemcache/test_memcache.py
- tests/datastore_pymemcache/tox.ini
- tests/testing_support/db_settings.py
- tests/testing_support/util.py
* Importing pymemcache tests from internal repo.
PYTHON-3803
> PYTHON-3803 pymemcache Tests

- .github/workflows/tests.yml
- tests/datastore_elasticsearch/conftest.py
- tests/datastore_elasticsearch/test_connection.py
- tests/datastore_elasticsearch/test_database_duration.py
- tests/datastore_elasticsearch/test_elasticsearch.py
- tests/datastore_elasticsearch/test_instrumented_methods.py
- tests/datastore_elasticsearch/test_mget.py
- tests/datastore_elasticsearch/test_multiple_dbs.py
- tests/datastore_elasticsearch/test_trace_node.py
- tests/datastore_elasticsearch/test_transport.py
- tests/datastore_elasticsearch/tox.ini
- tests/testing_support/db_settings.py
- tests/testing_support/fixtures.py
* Imports elasticsearch tests from internal repo.
* Adds elasticsearch 7 testing.
* Reduces matrix for older elasticsearch versions.
PYTHON-3789
> PYTHON-3789 elasticsearch Tests

- .github/workflows/tests.yml
- tests/datastore_pyelasticsearch/conftest.py
- tests/datastore_pyelasticsearch/test_pyelasticsearch.py
- tests/datastore_pyelasticsearch/tox.ini
* Import pyelasticsearch tests from internal repo.
* Cleanup tox.ini to remove extension based testing.
> pyelasticsearch Tests

- .github/workflows/tests.yml
* Pin `setup-python` action to known good version using git sha.
* Following recommendations in [GHA's docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses)
> Pin setup-python action

- newrelic/hooks/framework_grpc.py
* Fix incorrect wrapper for grpc instrumentation on `_MultiThreadedRendezvous._next`
PYTHON-3838
> Fix grpc instrumentation wrapping error

- tests/testing_support/fixtures.py
* Implement minor changes to coverage to allow it to be run in parallel.
* This allows us to run coverage on GHA should we choose to do so in the near future.
> Parallel Coverage

- .github/workflows/tests.yml
* Reorder python versions.
* This change makes tox run on CPython 3.9 instead of PyPy2. 
For most contributions it is strongly …
> Reorder python versions

- newrelic/api/web_transaction.py
- tests/agent_features/test_web_transaction.py
Thanks to @eykd for the detailed bug report! ❤️ 
This PR fixes a crash that occurs when non-ascii HTTP referers are passed to ASGI applications. The crash is fixed by ensuring the query string value is a decoded string (rather than bytes) prior to calling urlsplit when removing the query string from the referer. A regression test is included.
Fixes: #35
> Fix crash on non-ascii http referer. #35

- newrelic/hooks/external_httpx.py
- tests/external_httpx/conftest.py
- tests/external_httpx/test_client.py
This pull request adds functionality to process response headers and add a response status code attribute. It includes tests to verify CAT headers and status code for async and sync clients.
#103 
For most contributions …
> Add httpx response processing. #103

- tests/component_djangorestframework/urls.py
- tests/component_tastypie/urls.py
- tests/framework_django/urls.py
* Fix failing django tests with backwards compatible import changes.
N/A
> Fix django url import error

- newrelic/hooks/external_httpx.py
- tox.ini
This pull request includes a fix in the use of getattr() to grab response headers for httpx.
For most contributions it is strongly recommended to add additional …
> Fix httpx response header logic.

- tox.ini
uhashring dropped support for Python 2.7 in their 2.0 release. Since bmemcached installs this package, this PR pins a previous version of uhashring so we can continue to support Python 2.7.
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTI …
> Pin version of uhashring to support py27 for bmemcached.

- newrelic/api/asgi_application.py
Stack trace:
[2021-02-14 05:24:40 +0000] [21] [ERROR] Exception in ASGI application
Traceback (most recent call last):
File "/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File "/venv/lib/python3.8/site-packages/newrelic/api/asgi_application.py", line 332, in nr_async_asgi
with ASGIWebTransaction(
File "/venv/lib/python3.8/site-packages/newrelic/api/asgi_application.py", line 229, in __init__
host, port = scope["server"] = tuple(scope["server"])
TypeError: 'NoneType' object is not iterable
- "GET / HTTP/1.0" 500
Exception ignored in: …
> Fixes a bug that when using uvicorn and nginx with an upstream server via a unix socket results in a TypeError.

- newrelic/api/log.py
Refactors the `api.log.NewRelicContextFormatter`, so that converting the log record to a dict, and serializing to JSON, are achievable separately.
This change makes it easy to add the data exposed by `NewRelicContextFormatter` in custom formatters.
Without this change, a custom formatter has essentially two options:
1. Call `NewRelicContextFormatter.format`, deserialize the returned JSON, extend as desired, then re-serialize.
2. Copy the logic from `NewRelicContextFormatter`. This is undesirable for many reasons, not the least of which is that we can only …
> Refactor NewRelicContextFormatter, add log_record_to_dict

- newrelic/config.py
- setup.py
This PR removes the agent's Python 3.5 deprecation warning and updates `setup.py` to exclude 3.5.
> Cleanup for completed Python 3.5 deprecation.

- newrelic/api/log.py
- newrelic/api/time_trace.py
- newrelic/core/attribute.py
- newrelic/core/stats_engine.py
- newrelic/core/transaction_node.py
- tests/agent_features/test_attributes_in_action.py
- tests/agent_features/test_error_events.py
- tests/agent_features/test_high_security_mode.py
- tests/agent_features/test_logs_in_context.py
- tests/agent_features/test_span_events.py
- tests/testing_support/fixtures.py
* Add `error.expected` attribute to span events, and error events. Currently always false.
* Add scaffolding for error rule matching logic.
Closes #194
For most contributions it is strongly recommended to add additional …
> Expected Error Attribute

- newrelic/api/time_trace.py
- newrelic/config.py
- newrelic/core/config.py
- newrelic/core/stats_engine.py
- newrelic/newrelic.ini
- tests/agent_features/test_configuration.py
- tests/agent_features/test_ignore_expected_errors.py
This PR deprecates the  error_collector.ignore_errors setting in favor of  error_collector.ignore_classes setting.
Closes #192.
> Deprecate error_collector.ignore_errors setting.

- tox.ini
* Disables flask tests for latest version, pinning to versions <2. 
* Changes base branch name of werkzeug and flask to main.
N/A
exercise …
> Temporarily disable flask tests for v2 release.

- newrelic/agent.py
- newrelic/api/application.py
- newrelic/api/time_trace.py
- newrelic/api/transaction.py
- newrelic/core/agent.py
- newrelic/core/application.py
- newrelic/core/stats_engine.py
- newrelic/core/transaction_node.py
- tests/agent_features/test_ignore_expected_errors.py
- tests/agent_features/test_notice_error.py
* Add new `notice_error` api to conform to the standards of other agents.
* Forward old record_exception calls to new API.
* Add deprecation warning to record_exception.
Closes #196
Closes #197
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRI …
> Add notice_error API

- newrelic/api/log.py
- newrelic/api/time_trace.py
- newrelic/common/object_names.py
- newrelic/core/config.py
- newrelic/core/stats_engine.py
- tests/agent_features/test_ignore_expected_errors.py
* Adds support for ignore/expected status_codes within notice_error.
* Encapsulate parsing of message, and names from exceptions for reusability.
* Add testing for status_codes functionality.
* Add testing for mixed ignore and expected settings with overrides.
* Expand test file to include all current cases.
Closes #202 …
> Add ignore/expected status codes API to notice_error

- newrelic/api/log.py
- tests/agent_features/test_logs_in_context.py
- Fix NewRelicContextFormatter converts all extra log attributes to strings (resolves #21).
- Remove whitespaces from JSON log output.
NewRelicContextFormatter converts all extra log attributes to strings. This PR changes the behavior so that attributes are only converted to string if JSON serialization is not possible (by using `default=str` argument). This allows nested dictionary types to be used as log attributes.
For example:
```python
logging.info("Hello world!", extra={"integer": 123, "nested": {"foo": "bar"}})`
```
Before changes:
```json
{"message": "Hello world!", "integer": "123", "nested": "{'foo': 'bar'}"}
```
After changes (whitespaces removed, integer≠string, dictionary≠string):
```json
{"message":"Hello world!","integer":123,"nested":{"foo":"bar"}}
``` …
> Fix NewRelicContextFormatter converts all extra log attributes to strings

- newrelic/api/application.py
- newrelic/api/time_trace.py
- newrelic/api/transaction.py
- newrelic/core/agent.py
- newrelic/core/application.py
- newrelic/core/stats_engine.py
- tests/agent_features/test_ignore_expected_errors.py
- tests/testing_support/fixtures.py
* Add previous functionality back to notice_error api.
* ignore and expected arguments now can take an iterable of class names.  
* Reduce record_exception functions to include no logic and simply redirect to notice_error
* Remove some duplicated logic in notice_error for exc_info=None
Closes #214 …
> Add iterable logic to notice_error

- newrelic/admin/validate_config.py
- newrelic/api/transaction.py
- newrelic/api/wsgi_application.py
- tests/agent_features/test_asgi_distributed_tracing.py
- tests/agent_features/test_attributes_in_action.py
- tests/agent_features/test_distributed_tracing.py
- tests/agent_features/test_error_events.py
- tests/agent_features/test_exception_messages.py
- tests/agent_features/test_high_security_mode.py
- tests/agent_features/test_ignore_expected_errors.py
- tests/agent_features/test_priority_sampling.py
- tests/agent_features/test_span_events.py
- tests/agent_features/test_supportability_metrics.py
- tests/cross_agent/test_distributed_tracing.py
- tests/cross_agent/test_w3c_trace_context.py
- tests/testing_support/fixtures.py
- tests/testing_support/sample_applications.py
- tests/testing_support/sample_asgi_applications.py
This PR removes all outstanding uses of the record_exception API in the current agent codebase and replaces them with the new notice_error API.
Closes #209
> Remove record_exception uses in codebase.

- newrelic/hooks/database_dbapi2.py
- newrelic/hooks/database_sqlite.py
- tests/datastore_sqlite/test_database.py
* Fixes issue where generators are consumed by instrumentation in sqlite `connection.executemany`. 
* Add testing for executemany and generators on cursor and connection for sqlite.
Closes #179 
For most contributions …
> Fix sqlite connection executemany instrumentation.

- newrelic/api/log.py
- tests/agent_features/test_logs_in_context.py
* Add safe_str method to NewRelicContextFormatter to prevent all possible crashes.
N/A
> Add safe_str method to NewRelicContextFormatter

- .github/workflows/deploy.yml
* Fix an issue with `aws s3 cp` not detecting region.
N/A
> Add default aws region to deploy

- newrelic/core/agent_protocol.py
* Previously error messages for 410s would log content of response from data collector which includes reason for disconnect. Restoring this behavior.
* Add content back to 410 logging messages
* Correct `content` extra to use response content, instead of request payload, matching original implementation.
N/A …
> Fix logging in http exceptions

- newrelic/samplers/memory_usage.py
- tests/agent_unittests/test_sampler_metrics.py
Currently, the agent yields up total memory metrics for each detected PID. This PR adds a non PID specific total memory metric for compatibility with the query being used in the NR UI for the _All hosts by memory usage_ graph (found in the Charts section of the Summary page).
> Add non PID specific total memory metric.

- newrelic/hooks/framework_flask.py
- tests/framework_flask/test_not_found.py
- tests/framework_flask/test_user_exceptions.py
This PR adds an additional instrumentation point for register_error_handler for compatibility with Flask v2. 
Closes #234
> Update error handler instrumentation point for Flask v2 

- tests/framework_flask/_test_application.py
- tests/framework_flask/_test_blueprints.py
- tests/framework_flask/_test_views.py
- tests/framework_flask/conftest.py
- tests/framework_flask/test_application.py
- tests/framework_flask/test_blueprints.py
- tests/framework_flask/test_middleware.py
- tests/framework_flask/test_views.py
- tox.ini
* Add testing for flask async views.
* Centralize logic for flask version skipping.
Closes #233 
> Flask async view tests

- newrelic/hooks/framework_flask.py
- tests/framework_flask/_test_application.py
- tests/framework_flask/_test_application_async.py
- tests/framework_flask/_test_blueprints.py
- tests/framework_flask/_test_views.py
- tests/framework_flask/_test_views_async.py
- tests/framework_flask/conftest.py
- tests/framework_flask/test_application.py
- tests/framework_flask/test_blueprints.py
- tests/framework_flask/test_middleware.py
- tests/framework_flask/test_not_found.py
- tests/framework_flask/test_user_exceptions.py
- tests/framework_flask/test_views.py
- tox.ini
* Add support for Flask v2
* Add testing for additional flask functionality
Closes #243 
> Flask v2 Support

- newrelic/hooks/framework_pyramid.py
- tests/framework_pyramid/test_application.py
- tests/framework_pyramid/test_cornice.py
For the Pyramid framework, use a higher priority=2 when calling set_transaction_name
* in the view_handler_wrapper (for non-exception views only)
* for both calls in the default_view_mapper_wrapper._wrapper since we have an instance of the registered view_callable in both cases
similar to how exception handler prioritization is handled in the Flask hooks module.
https://github.com/newrelic/newrelic-python-agent/issues/236
For most contributions it …
> Pyramid (transaction naming): lower exception view precedence

- newrelic/hooks/external_httpx.py
- tests/external_httpx/test_client.py
Fixes: #249 
The crash is caused by instrumentation patches being applied after a client is instantiated. This results in the `_event_hooks` attribute being present in the `Client.__dict__` but the nr hook setter hasn't run.
> Fix an httpx crash caused by import ordering issues.

- newrelic/samplers/memory_usage.py
* Fixed: On kernels such as BSD memory metrics have values of None, causing a division crash.
N/A
> Fix crash in memory metric calculations

- newrelic/api/graphql_trace.py
- newrelic/config.py
- newrelic/core/graphql_node.py
- newrelic/hooks/framework_graphql.py
- tests/framework_graphql/_target_application.py
- tests/framework_graphql/conftest.py
- tests/framework_graphql/test_application.py
- tests/framework_graphql/test_application_async.py
- tox.ini
* Remove unused instrumentation
* Clean up testing to be more thorough and remove duplicates
* Add ignored and introspection fields to deepest path traversal
* Set transaction name according to spec
* Moves async testing to a separate test file
* Removes graphql 2.1.0 from test matrix based on three year support policy
Closes #280 
Closes #265
> GraphQL Cleanup

- newrelic/hooks/framework_graphql.py
- tests/framework_graphql/_target_application.py
- tests/framework_graphql/conftest.py
- tests/framework_graphql/test_application.py
- tests/framework_graphql/test_application_async.py
This PR adds logic to obtain the selection set(s) for fragment spreads and traverse through them to find the deepest unique path for transaction naming. 
Closes #292
> GraphQL Fragment Spread Logic

- .github/stale.yml
This PR updates the repo's stale workflow labelling and auto-closing functionality. Auto-closing has been disabled in favor of maintainers verifying and closing issues manually. The `staleLabel` has also been updated from `wontfix` to `stale` as the original label was misleading.
> Update stale workflow

- .github/workflows/deploy.yml
Co-authored-by: Tim Pansino <tpansino@newrelic.com>
Co-authored-by: Lalleh Rafeei <lrafeei@newrelic.com>
This PR updates deploy.yml to use `cibuildwheel` and adds builds for aarch64 for Python 3. 
Closes #295.
> Update deploy.yml to support arm builds.

- newrelic/hooks/framework_graphql.py
Co-authored-by: lrafeei <lrafeei@users.noreply.github.com>
* Add try excepts to all binds in GraphQL instrumentation to prevent crashes in older applications.
Closes #304
> Protect GraphQL binds with try excepts

- newrelic/api/html_insertion.py
- newrelic/common/log_file.py
Minor issue: when compiling with Python 3.6+, we see `DeprecationWarning`'s for an "invalid escape sequence". To resolve, I updated places in the code where the warning is thrown with raw string notation.
We use the New Relic Python agent at work and one of our CI jobs recently started failing because it handled the `DeprecationWarning` as a `SyntaxError`. Did some investigating and found this blurb in the Python docs.
> Changed in version 3.6: Unrecognized escape sequences produce a DeprecationWarning. In a future Python version they will be a SyntaxWarning …
> Updated DeprecationWarnings about invalid escape sequences

- tox.ini
This PR temporarily disables testing of py36 on the latest uvicorn version by pinning the version to its preceding release (v0.14)
> Pin uvicorn version to v0.14 for py36 testing purposes.

- .github/workflows/tests.yml
This PR adds the develop prefix check to the GHA test workflow to ensure all tests are run when a develop-* branch is set as target.
> Add develop branch check to GHA test workflow.

- newrelic/newrelic.ini
This updates the default newrelic.ini to set distributed_tracing.enabled to True as a part of the DT by default effort.
> Enable DT in default newrelic.ini

- tox.ini
This PR adds new tox environments to run the tests against latest Django 3.2 and Python from 3.6 to 3.9 (supported Python version for Django 3.2)
https://github.com/newrelic/newrelic-python-agent/issues/343
There's no special setup for testing, the CI will run the tests in the new environments with tox.
> Add tests for Django 3.2

- newrelic/api/graphql_trace.py
- newrelic/core/graphql_node.py
- newrelic/hooks/framework_ariadne.py
- newrelic/hooks/framework_graphql.py
- newrelic/hooks/framework_strawberry.py
- tests/framework_ariadne/test_application.py
- tests/framework_ariadne/test_application_async.py
- tests/framework_ariadne/test_asgi.py
- tests/framework_ariadne/test_wsgi.py
- tests/framework_graphene/test_application.py
- tests/framework_starlette/test_graphql.py
- tests/framework_strawberry/test_application.py
- tests/framework_strawberry/test_application_async.py
- tests/framework_strawberry/test_asgi.py
- tox.ini
This PR adds logic to store framework information to update metric names to include the specific product in use (ex: Ariadne, Strawberry, Graphene). It also includes the addition of framework metrics for the Graphene library.
Closes #358.
Closes #362.
> Add GraphQL Framework Info to Metrics

- tox.ini
This PR removes testing for pymongo<3.0 due to align with the agent's three year package version support policy.
> Drop testing for pymongo<3.0 

- .github/workflows/tests.yml
- newrelic/api/transaction.py
- newrelic/console.py
- newrelic/core/agent.py
- newrelic/core/application.py
- newrelic/core/profile_sessions.py
- tests/agent_features/test_event_loop_wait_time.py
- tests/agent_unittests/conftest.py
- tests/base_requirements.txt
- tests/framework_sanic/_target_application.py
- tox.ini
This PR adds testing setup for Python 3.10rc2.
> Add python 3.10 test setup. 

- tests/agent_unittests/test_http_client.py
* Fix SSL Context deprecation warnings in tests.
Closes #389
> Fix SSL Context Deprecation Warning

- newrelic/api/log.py
- newrelic/api/time_trace.py
- newrelic/api/transaction.py
- newrelic/core/config.py
- newrelic/core/stats_engine.py
- tests/agent_features/test_logs_in_context.py
- tests/agent_features/test_notice_error.py
* Fix handling of settings in `error_matches_rules` to use the same settings as the call to `notice_error`, to be sure application settings are properly observed.
* Reorder `complete_root` and `notice_error` calls in `Transaction.__exit__` to fix missing settings issues.
* Remove `error.expected` attribute from logs in context IF there is no active transaction, as there is no reliable way to retrieve an application from within the context formatter otherwise.
Closes #378
* Modified existing tests to ensure they failed when these changes were not present.
* Added new tests for logs in context to capture inside/outside transaction behavior of errors
> Fix notice_error Rules Matching Settings Handling

- .github/workflows/deploy-python.yml
* This may build with the release candidate until `cibuildwheel` updates itself, but that shouldn't be an issue.
N/A
> Add Python 3.10 Builds

- newrelic/core/context.py
- newrelic/core/trace_cache.py
- newrelic/hooks/adapter_asgiref.py
- newrelic/hooks/framework_fastapi.py
- newrelic/hooks/framework_starlette.py
- setup.py
- tests/framework_fastapi/conftest.py
- tests/framework_fastapi/test_application.py
- tests/framework_flask/test_views.py
* A bug in context propagation resulting from instrumentation of Starlette's `run_in_threadpool` caused redundant instrumentation to issue `Runtime instrumentation error`s. This has been corrected.
* Refactor of existing context propagation to use centralized context manager API.
Closes #419
Negative testing done, `caplog` should be sufficient to catch regressions.
> Fix FastAPI Context Propagation

- setup.py
* Due to retries becoming enabled by default, gRPC will be pinned to an earlier version until compatibility can be ensured without causing retry storms.
> Pin gRPC<1.40

- newrelic/core/agent_streaming.py
- setup.py
- tox.ini
* Fix issue with gRPC subchannels staying open under infinite tracing
* Remove pinned gRPC version
* Refactor gRPC backoff to match connection spec
N/A
For most contributions it is strongly recommended to add additional …
> Fix infinite tracing spec compliance

- tests/datastore_elasticsearch/test_transport.py
This PR updates elastic search transport tests by adding Content-Type headers to `perform_request` calls (based on package version). This is necessary due to updates to elastic search's [compatibility header requirements](https://github.com/elastic/elasticsearch-py/commit/8aee058f80cf14b6f523a1996dee932ec925eacc).
> Fix elasticsearch tests for v7.16.0+

- tox.ini
This PR temporarily disables testing on the latest version of Django until v4 support is added to agent.
> Update Django tests

- tox.ini
A new zone (ap-southeast-3) was [added](https://github.com/spulec/moto/commit/cf2461a14e2d9d996f093372a244a800c5670cd9 ) to moto in v2.2.19. This PR updates the version of moto installed in the botocore tests to account for this change and alleviate a `KeyError`.
> Update moto version used in botocore tests.

- tox.ini
This PR drops Python 3.6 testing for Tornado. 
See: https://github.com/tornadoweb/tornado/commit/1f8aab8ba7340c7d2b146d989cfcc4e3482b0a6b
> Drop py36 testing for Tornado.

- tox.ini
* Strawberry v0.95.0 is incompatible with Starlette 0.18.0.
> Fix Strawberry Testing Versions

- tox.ini
Pyramid has dropped support for Python 3.6 on their master branch for upcoming release as seen [here](https://github.com/Pylons/pyramid/commit/c7250ee947d2804a54a272373758150cce9db539#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7). This PR updates the Pyramid testing matrix to reflect this change.
> Drop Python 3.6 testing for Pyramid master. 

- newrelic/common/streaming_utils.py
- newrelic/core/agent_streaming.py
Co-authored-by: Lalleh Rafeei <lrafeei@users.noreply.github.com>
Co-authored-by: Michael Goin <michaelgoin@users.noreply.github.com>
* Data loss with gRPC has been occurring when the data collectors issues a restart. This has been mostly mitigated with proper locking and safeguarding the stream buffer.
N/A
N/A
> Fix Lost Data in gRPC (Infinite Tracing)

- setup.py
Fixes the URL displayed in PyPI's website that directs to the New Relic Documentation
> Fix the URL to New Relic's Docs displayed in PyPI

- newrelic/hooks/framework_graphql.py
- newrelic/hooks/framework_graphql_py3.py
* The functions `graphql_impl` or `graphql` can in fact return coroutines in frameworks like Graphene. This patch correctly closes the trace after the coro executes.
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#testing-guideline …
> Fix GraphQL Impl Coros

- tox.ini
This PR pins the protobuf version used in mysql to less than 4.  This is a temporary fix since protobuf 4.21 was released then pulled.
> Pin protobuf version to < 4 (for now)

- newrelic/core/agent_streaming.py
- newrelic/core/config.py
* Protobuf v4 causes issues when importing agent_streaming, even when infinite tracing is disabled and the agent is not using gRPC. 
* Fix this issue by suppressing errors from the pb2 file at import time.
* When v4 is stable and released, will need additional work to ensure full compatibility.
Closes #545
> Fix gRPC / Protobuf incompatibilities

- newrelic/api/transaction.py
`threading.currentThread` was deprecated in Python 3.10 (October 2021) and will be removed in Python 3.12 (October 2023).
Replace with `threading.current_thread`, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
> Replace deprecated threading.currentThread with threading.current_thread

- tests/datastore_aredis/test_multiple_dbs.py
* Add a regression test that reproduces probably concurrency bugs in async redis instance reporting.
N/A
* This test is marked XFail to prove the existence of the bug and demonstrate a working regression test. The fix will come in a separate PR which removes the XFail marker.
> ARedis Concurrency Bug Regression Test

- newrelic/hooks/datastore_aioredis.py
- tests/datastore_aioredis/test_multiple_dbs.py
* Fix datastore information storage bug for concurrent calls.
> Fix AIORedis Concurrency Bug

- newrelic/config.py
- newrelic/hooks/datastore_redis.py
- tests/datastore_aredis/test_uninstrumented_methods.py
- tests/datastore_redis/test_uninstrumented_methods.py
* Add additional instrumentation points for all new client methods in Redis, as well as Redis Modules.
> Instrument All Redis Client Methods

- tox.ini
Versions of pika > 1.1.0 no longer support Python 2.7. This PR updates the tox matrix to reflect these changes.
> Update pika tox matrix.

- newrelic/core/config.py
- tests/testing_support/fixtures.py
This PR flips the switch on `application_logging.forwarding.enabled` to turn it on by default.
> Enable log forwarding by default.

- newrelic/common/agent_http.py
- newrelic/core/config.py
- tests/agent_unittests/test_harvest_loop.py
- tests/agent_unittests/test_http_client.py
- tests/testing_support/fixtures.py
This PR enables log forwarding by default and corrects the Python agent data usage supportability metric naming scheme. It also addresses a bug related to compressed byte calculation.
> Enable log forwarding by default. 

- .github/workflows/deploy-python.yml
- .github/workflows/mega-linter.yml
- .github/workflows/tests.yml
- .gitignore
- .mega-linter.yml
* Upgrade MegaLinter to v6 using automated upgrader
* Also happened to upgrade all calls to actions/checkout to v3, leaving that in as well.
> Upgrade MegaLinter to v6

- tox.ini
* Django released a new version incompatible with the current TastyPie. Pinning old version.
All tastypie tests (except PyPy3.6 which can't be installed on latest MacOS version) pass locally, probably not possible to get the GHA checks to pass right now.
> Fix django version for tastypie

- tests/coroutines_asyncio/test_context_propagation.py
- tox.ini
* Removes uvloop from PyPy testing for `coroutines_asyncio` as uvloop is not listed as compatible with PyPy and cannot be installed on PyPy3.7+.
Blocks #590
> Fix PyPy coroutines testing to exclude uvloop

- newrelic/hooks/logger_loguru.py
- tests/logger_loguru/test_stack_inspection.py
Loguru looks at the stack trace to determine the caller's module and function name for logging. In the example below, we are calling `logger.info("initialized")` from inside module `__main__` in function `my_function`:
```
2022-08-04 17:28:30.883 | INFO     | __main__:my_function:7 - initialized
```
Loguru looks two levels up (`_log` <- `info` <- `my_function`) in the stacktrace. Newrelic's `loguru._logger` hook breaks this by adding one call in between (`_log` <- `wrap_log` <- `info` <- `my_function`), which causes loguru to log instead:
```
2022-08-04 …
```
> Fix loguru detection of module/function name

- newrelic/core/environment.py
- tests/agent_unittests/test_environment.py
Capture third party modules and their version.
* [Add python app modules version information to the data published to agent_lifecycle_event](https://issues.newrelic.com/browse/NR-35286)
* https://github.com/newrelic/newrelic-python-agent/issues/542
> Capture module versions

- newrelic/config.py
- newrelic/hooks/framework_sanic.py
- tests/framework_sanic/_target_application.py
- tests/framework_sanic/conftest.py
- tox.ini
Starting in [Sanic version 21.9.0](https://sanic.readthedocs.io/en/stable/sanic/changelog.html#version-21-9-0), Sanic added a TouchUp metaclass that rewrites methods on the Sanic class effectively undoing our instrumentation wrapping on startup of the server. This adds back our instrumentation wrapping after it is undone by wrapping the TouchUp metaclass.
This fixes [To support instrumentation on Sanic 21.9 / 21.12](https://issues.newrelic.com/browse/NR-40216)
Fixes #608
> Add support for Sanic.TouchUp metaclass

- newrelic/samplers/memory_usage.py
* PID used in memory sampler for metric naming is incorrect in forked processes. Fixed by always getting the PID again.
#566
> Fix PID in Memory Sampler

- tox.ini
* Temporarily disable failing tests for GraphQL master branch until they've fixed build issues.
> Disable GraphQL Master Tests

- tests/agent_features/test_ignore_expected_errors.py
- tests/testing_support/fixtures.py
Previously, if notice_error did not record an error then the
validate_error_event_attributes_outside_transaction fixture would silently pass. This
is because the validation would not ever run since it was decorated in a stats_engine
notice error block. By moving the validation outside of this decorator, now the
validation will run even if no error is recorded in the stats_engine. This has been
fixed so now the fixture raises if no error is recorded at all.
Along with this change fix the following pylint errors:
* tests/testing_support/fixtures.py:2400:46: E0601: Using variable 'backup' before assignment (used-before-assignment)
* tests/testing_support/fixtures.py:2423:37: E0601: Using variable 'backup' before assignment (used-before-assignment)
* tests/testing_support/fixtures.py:2447:59: …
> Fix silent failure in validator fixture

- newrelic/hooks/messagebroker_confluentkafka.py
- tests/messagebroker_confluentkafka/conftest.py
- tests/messagebroker_confluentkafka/test_producer.py
- tox.ini
This PR fixes two bugs in our confluent-kafka instrumentation both related to the producer arguments:
1. Fixes #643.
Previously the Producer.produce instrumentation did not support all arguments. Now it supports all arguments.
2. Fixes Producer.produce not supporting dict type for headers argument. Now it supports dict type and list of tuples.
Co-authored-by: Timothy Pansino <TimPansino@users.noreply.github.com>
Co-authored-by: Hannah Stepanek <hmstepanek@users.noreply.github.com>
> Support confluent-kafka produce arguments

- newrelic/hooks/framework_sanic.py
- tests/framework_sanic/conftest.py
- tests/framework_sanic/test_application.py
- tox.ini
Fix instumentation for sanic 22.0.9
In 22.9.0 sanic introduced an API to control middleware ordering which broke 2 things:
* The addition of the new middleware mixin included a new method called `finalize_middleware` that sets the middleware to be used on the request.route during the `app._startup`. In order to register new middleware the `finalize_middleware` must be called, otherwise the app will use the previously registered middleware that was registered before `app._startup`.
* The middleware mixin wrapped certain middleware functions causing the name of the transaction and function trace to be the name of the mixin instead of the middleware function.
https://issues.newrelic.com/browse/NR-53906
> Fix instumentation for sanic 22.0.9

- newrelic/admin/record_deploy.py
Newrelic treats application names as case-insensitive server-side, but `newrelic-admin record-deploy` uses case-sensitive comparison. This PR fixes that
\-
Manual test
> Fix app id fetch in newrelic-admin record-deploy

- newrelic/api/database_trace.py
- newrelic/api/graphql_trace.py
- newrelic/api/transaction.py
- tests/agent_features/test_span_events.py
- tests/agent_features/test_time_trace.py
- tests/agent_features/test_transaction_trace_segments.py
* Fix crashes in finalizers for various trace types when settings has disappeared (such as a transaction being manually exited).
* Add parameterized tests to verify these no longer crash.
Closes #632
> Fix Trace Finalizer Crashes

- newrelic/hooks/framework_flask.py
- tests/component_flask_rest/test_application.py
- tests/framework_flask/test_views.py
Co-authored-by: Lalleh Rafeei <lrafeei@users.noreply.github.com>
Co-authored-by: Hannah Stepanek <hmstepanek@users.noreply.github.com>
* Flask class-based and method-based views currently report the class name as the `code.function` source, causing Code Level Metrics to not work with them. This PR fixes that.
> Fix Flask view support in Code Level Metrics

- .github/actions/setup-python-matrix/action.yml
- .github/workflows/deploy-python.yml
- newrelic/hooks/framework_aiohttp.py
- newrelic/hooks/framework_sanic.py
- setup.py
- tests/agent_features/_test_async_coroutine_trace.py
- tests/agent_features/test_async_timing.py
- tests/agent_features/test_coroutine_trace.py
- tests/agent_features/test_coroutine_transaction.py
- tests/agent_features/test_event_loop_wait_time.py
- tests/agent_unittests/conftest.py
- tests/agent_unittests/test_utilization_settings.py
- tests/cross_agent/test_collector_hostname.py
- tests/cross_agent/test_utilization_configs.py
- tests/framework_aiohttp/_target_application.py
- tests/framework_aiohttp/conftest.py
- tests/framework_aiohttp/test_client.py
- tests/framework_aiohttp/test_client_cat.py
- tests/framework_aiohttp/test_externals.py
- tests/framework_aiohttp/test_middleware.py
- tests/framework_aiohttp/test_server.py
- tests/framework_aiohttp/test_server_cat.py
- tests/framework_aiohttp/test_ws.py
- tests/framework_tornado/_target_application.py
- tests/framework_tornado/test_server.py
- tox.ini
> Add Python 3.11 Support

- .github/actions/setup-python-matrix/action.yml
* Upgrades dev python 3.11 version to stable.
> Add Python 3.11 stable release to GHA

- newrelic/config.py
- tests/component_flask_rest/test_application.py
- tox.ini
Fix failing flask_rest tests
* Drop support for flask-restplus.
* The latest version of flask-restx dropped support for 2.7 so split the flask_rest tests up into 2 tox envs.
> Fix failing flask_rest tests

- tests/external_botocore/test_botocore_sqs.py
- tox.ini
Fix failing botocore tests
In botocore >= 1.29.0, the url for queue changed so fix the tests to expect the new url.
> Fix failing botocore tests

- newrelic/agent.py
Add record_log_event to public api
Fixes [Publish record_log_event API](https://issues.newrelic.com/browse/NEWRELIC-4994).
https://github.com/newrelic/docs-website/pull/10176.
> Add record_log_event to public api

- newrelic/config.py
- newrelic/hooks/component_sentry.py
This PR patches `sentry-sdk`  to fix a bug that causes incorrect ASGI application version detection with our wrapt function wrappers. To fix this, we now instrument the `_looks_like_asgi3()` function to bind out the wrapped app in sentry in order to unwrap it to be able to detect the proper ASGI version.
Related Issue: #117
> Add patch for sentry SDK to correct ASGI v2/v3 detection.

- tox.ini
* Fixes an issue with older versions of pip on Python 2.7 causing crashes related to the shared cache.
> Fix Pip Concurrency Issues

- .github/actions/setup-python-matrix/action.yml
- .github/workflows/tests.yml
* The `ubuntu-latest` tag changed from 20.04 to 22.04, and 22.04 does not provide python 2.7 in the tools cache. This PR pins to the previous runner version for now.
* setup-python@v3 is emitting deprecation warnings, fixed by upgrading to v4.
Related to https://github.com/actions/setup-python/issues/543
> Pin Github Actions Runner to Ubuntu 20 for Py27

- newrelic/hooks/messagebroker_confluentkafka.py
- tests/messagebroker_confluentkafka/test_producer.py
Fixes a bug where topic provided as a keyword argument can crash confluent kafka producers.
> Fix Confluent Kafka Producer Arguments

- newrelic/hooks/datastore_redis.py
- tox.ini
Fix tornado master tests & instrument redis 4.3.5
1. Drop 3.7 testing from tornado master.
* Tornado master dropped support for 3.7
1. Instrument new redis 4.3.5 client methods.
> Fix tornado master tests & instrument redis 4.3.5

- newrelic/api/application.py
This fixes Missing information from Celery workers when using MAX_TASKS_PER_CHILD issue.
Previously, if celery was run with the --loglevel=INFO flag, an agent instance would be created for the main celery process and after the first worker shutdown, all following worker's agent instances would point to that agent instance instead of creating a new instance. This was root caused to incorrectly creating an agent instance when application activate was not set. Now no agent instance will be created for the main celery process.
> Fix bug in celery where workers don't report data

- newrelic/config.py
* Flask Restplus hook was removed, adding it back. 
* This module is now unmaintained and outside our support window, and will have no tested support going forward but existing hooks and functionality will remain in place.
Partially Reverts #683
> Revert Removal of Flask Restplus Hook

- .github/actions/setup-python-matrix/action.yml
- newrelic/core/code_level_metrics.py
- tests/agent_features/_test_code_level_metrics.py
- tests/agent_features/test_code_level_metrics.py
* Previously either no data was reported or a crash occurred (depending on agent version) when using a class created using the [3 argument type constructor](https://docs.python.org/3/library/functions.html?highlight=type#type). Fixed and properly returns without line number (which is unavailable).
* Pin tox major version to v3 until CI can be fixed.
Closes #515
> Fix Type Constructor Classes in Code Level Metrics

- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_metric_scorers.py
Include training step in metric scorer name.
It is common when training a model to continue to train it with new data until it reaches a certain accuracy level. In these cases, since we are uploading the scorer results as an attribute we need to distinguish between different scorer calls. Otherwise they will be replaced with the most recent scorer call's results. In order to do this we increment a counter each time fit is called in order to keep track of the model's re-trainings.
Fixes https://issues.newrelic.com/browse/NR-73174.
> Include training step in metric scorer name

- tests/framework_sanic/test_application.py
- tox.ini
This PR fixes the tests for Sanic when Sanic v22.12 was released.  Changes in `register_middleware` affected tests.
Starlette v0.23.1 is pinned as latest for now.
> Fix sanic and starlette tests

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_svm_models.py
Add function traces around the following methods in the sklearn SVM models:
- fit
- predict
> Add svm model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_semi_supervised_models.py
Add function traces around the following methods in the sklearn semi supervised models:
- fit
- predict
- predict_log_proba
- score
> Add semi supervised model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_pipeline_models.py
Add function traces around the following methods in the sklearn pipeline models:
- fit
- predict
- score
- transform
> Add pipeline model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_neural_network_models.py
Add function traces around the following methods in the sklearn neural network models:
- fit
- predict
- predict_log_proba
- transform
> Add neural network model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_neighbors_models.py
Add function traces around the following methods in the sklearn neighbors models:
- fit
- predict
- transform
> Add neighbors model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_mixture_models.py
Add function traces around the following methods in the sklearn mixture models:
- fit
- predict
- score
> Add mixture model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_model_selection_models.py
Add function traces around the following methods in the sklearn model selection models:
- fit
- predict
- predict_log_proba
- score
> Add model selection model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_naive_bayes_models.py
Add function traces around the following methods in the sklearn naive bayes models:
- fit
- predict
- predict_log_proba
> Add naive bayes model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_multioutput_models.py
Add function traces around the following methods in the sklearn multioutput models:
- fit
- predict
- score
> Add multioutput model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_multiclass_models.py
Add function traces around the following methods in the sklearn multiclass models:
- fit
- predict
> Add multiclass model function traces

- newrelic/config.py
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_ensemble_models.py
- tests/mlmodel_sklearn/test_kernel_ridge_models.py
Add function traces around the following methods in the sklearn kernel ridge models:
- fit
- predict
> Add kernel ridge model function traces

- newrelic/hooks/datastore_redis.py
This PR instruments the "card" method that was added in Redis v4.4.2.
> Add "card" method to instrument in Redis

- newrelic/hooks/logger_logging.py
- tests/logger_logging/test_local_decorating.py
Reverts newrelic/newrelic-python-agent#736
It looks like what was implemented in [logging](https://source.datanerd.us/logging/log-parser-consumer/pull/933) is not necessarily compatible with this change so reverting for now.
> Revert "Fix log decorating to be JSON compatible"

- newrelic/config.py
- newrelic/hooks/datastore_aioredis.py
`aioredis` is included to redis-py since version 4.2.0rc1 as `redis.asyncio` (https://github.com/redis/redis-py/pull/1899). This PR adapts the current `newrelic.hooks.datastore_aioredis` for supporting `redis.asyncio`.
> Support `redis.asyncio`

- newrelic/core/transaction_node.py
- tests/agent_features/test_attributes_in_action.py
Add apdexPerfZone and nr.apdexPerfZone attribute to Web Transaction event intrinsic attributes.
Co-authored-by: Enriqueta De Leon <deleonenriqueta@users.noreply.github.com>
Co-authored-by: Kate Anderson <kanderson250@users.noreply.github.com>
Co-authored-by: Mary Martinez <mary-martinez@users.noreply.github.com>
This PR 
- Updates transaction_node.py to include the attribute "apdexPerfZone".
- Moves "nr.apdexPerfZone" to be appended for all Web transaction events instead of just Cross Application Transaction events. 
Updates test_attributes_in_action to validate both "apdexPerfZone" and "nr.apdexPerfZone".
> Add apdexPerfZone attribute to Transaction.

- newrelic/common/package_version_utils.py
- newrelic/hooks/datastore_aioredis.py
- tests/agent_unittests/test_package_version_utils.py
- tests/datastore_aioredis/conftest.py
- tests/datastore_aioredis/test_instance_info.py
- tests/datastore_aioredis/test_multiple_dbs.py
- tests/datastore_aioredis/test_uninstrumented_methods.py
- tox.ini
* Adapt `aioredis` tests to the moved version of the library located at `redis.asyncio` in the `redis-py` lib.
* Add tox envs for `redis.asyncio` separate from `aioredis` or existing `redis-py` envs to avoid as much confusing overlap as possible.
* Add `get_package_version_tuple` to replace common logic of splitting strings to tuples with safer alternative.
Testing for #744
Related to #747
> Redis Asyncio Testing

- tests/framework_starlette/test_bg_tasks.py
- tox.ini
With the release of [Starlette v0.23.1](https://github.com/encode/starlette/pull/1940), the check to see if "more_body" exists is removed
> Fix tests in starlette v0.23.1

- .github/scripts/retry.sh
- tox.ini
* Fixes intermittent pip failures using retry with exponential backoff.
* Should drastically reduce the amount of manually test reruns required and allow merge queue to be useful.
> Add Retry to Pip Install

- tests/agent_features/test_priority_sampling.py
* Due to randomness in the adaptive sampler, PyPy tests are randomly failing today (no idea why now) where the priority queue automatically adds 1 to the priority when marking a transaction as definitively sampled. Fixing existing test to account for this while still testing what it's aimed at.
> Fix PyPy Priority Sampling Test

- newrelic/core/application.py
- tests/agent_streaming/test_infinite_tracing.py
* Add feature toggle metrics for infinite tracing to supportability on agent startup. Note these are only sent ONCE and not on each harvest.
* Add testing for the new supportability metrics.
> Infinite Tracing Supportability Feature Toggle Metrics

- tests/agent_features/test_transaction_event_data_and_some_browser_stuff_too.py
* Test recently started failing as a result of #379. Fixed by disabling DT to prevent span event erroneously failing the test.
* Unknown why this test went 500 days without having issues, and even now only seems to affect PyPy 3.7 in CI. Locally these tests seem to all fail fairly consistently.
> Fix DT settings for transaction feature toggles test

- .github/mergify.yml
* Per an email received from mergify, this PR changes rules to avoid checking any PRs that are already merged to lessen impact on the GitHub API.
> Exclude Merged PRs Mergify Actions

- tests/datastore_redis/test_instance_info.py
This PR fixes redis tests for v4.5.2 (latest) based on changes made in this PR: https://github.com/redis/redis-py/pull/2588.
> Fix instance info tests for redis.

- newrelic/hooks/framework_django.py
- tests/component_djangorestframework/test_application.py
- tests/framework_django/test_application.py
- tests/framework_django/test_asgi_application.py
This removes the following middlewares from being instrumented in an effort to reduce the number of spans created when instrumenting django:
* CsrfViewMiddleware
* XFrameOptionsMiddleware
* MessageMiddleware
* CsrfViewMiddleware
* CommonMiddleware
* SecurityMiddleware
[Spike DT Improvements](https://issues.newrelic.com/browse/NR-91358)
> Reduce number of spans in django framework

- newrelic/hooks/datastore_redis.py
- tests/datastore_redis/test_instance_info.py
* Latest version of redis changed defaults values for connections. Fix logic to handle this.
* connection.port now has a default value while connection.path does not. Reorder detection of socket path vs port for `port_path_or_id` attribute to fix this.
* Reverts #784 which changed the tests to assert the new behavior, which was incorrect.
> Fix Redis Instance Info

- newrelic/hooks/framework_graphql.py
- tests/framework_graphql/test_application.py
* A bug was introduced in GraphQL instrumentation when not running within a transaction in v8.7.1.
* Adds a settings lookup guard to address this crash.
Closes #786
> Guard GraphQL Settings Lookup

- newrelic/common/signature.py
- newrelic/hooks/logger_loguru.py
- tests/agent_unittests/test_siganture.py
- tests/agent_unittests/test_signature.py
* Signatures changed in loguru v0.7.0 breaking local decorating and call stack adjustments. Fixed with auto-signature implementation.
> Fix Loguru Instrumentation for v0.7.0

- .github/actions/setup-python-matrix/action.yml
- .github/workflows/tests.yml
- tox.ini
Pin virtualenv to the last version before they stopped supporting Python 2.7 (f strings are now used, which are only supported in Python 3)
Pin pip because install-options was deprecated (we use this to install pycurl with openssl).
> Pin virtualenv, fix pip arg deprecation & disable kafka tests

- tests/datastore_aioredis/conftest.py
- tests/datastore_aioredis/test_get_and_set.py
- tests/datastore_aioredis/test_transactions.py
- tox.ini
* Pin asgiref to fix failing tastypie tests.
* asgiref==3.7.1 seems to have broken support for Python <3.10. 
* Fix concurrency based aioredis failures with PID unique keys.
> Fix Testing Failures

- tox.ini
Removing the `[]` broke pytest filtering when I switched the tests to wrap pytest in coverage. This reverts that change.
Before fix this would not filter the tests:
`tox -e python-cross_agent-pypy-without_extensions -- -k test_collector_hostname`
With this fix now it does.
> Fix pytest test filtering when running tox

- .github/workflows/tests.yml
* Changes previous `set-output` syntax to newer environment files for Github Actions.
> Fix set output warning using new GHA syntax

- .github/containers/Dockerfile
- .github/containers/Makefile
- .github/containers/install-python.sh
- .github/workflows/build-ci-image.yml
- .github/workflows/tests.yml
* Fixed and standardized the following
* CI Image was tagged with the repository name instead of adding `-ci`. 
* Workflows used a hardcoded image name that didn't include `newrelic-` in the image name. 
* Cleaned up scripting logic to be simpler.
* Pinned pypy2.7, as `pyenv latest -k pypy2.7` incorrectly returns `pypy2.7-5.10.0` instead of the correct `pypy2.7-7.3.11`. No new releases for pypy2.7 are expected, so this shouldn't affect anything.
> Fix CI Image Tagging

- .github/containers/Dockerfile
- tox.ini
* Remove non-root user from CI image.
* Pin virtualenv for tox to detect Python 2.7.
> Tweak CI Image

- .github/containers/Dockerfile
- .github/containers/requirements.txt
- .github/workflows/tests.yml
- newrelic/config.py
- tests/application_gearman/test_gearman.py
- tests/datastore_elasticsearch/test_connection.py
- tests/testing_support/db_settings.py
- tests/testing_support/validators/validate_tt_collector_json.py
- tox.ini
* Fix CI container configuration
* Add ODBC library headers
* Add timezone info
* Fix pinned version of virtualenv
* Add run option for host gateway, allowing port bindings to remain a way of have "multiple instances" for DB tests.
* Swap `libcurl` test runners to pure python.
* Configure git to fetch tags properly in CI.
* Revert disable of Py27 tests, and gearman instrumentation.
* Genericize gearman settings for CI vs local.
* Fix coverage paths for containers.
* Last test run before reverting container to `latest` tag that's unupdated: https://github.com/newrelic/newrelic-python-agent/actions/runs/5358678225
> Fix Tests on New CI

- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_inference_events.py
- tests/mlmodel_sklearn/test_ml_model.py
* Fix some name mismatches between the mlops sdk and the agent:
* model_name -> modelName
* numerical -> numeric
* type -> feature_/label_type
* value -> feature_/label_value
* event name -> inferenceData
> Fix attribute name mismatches from mlops sdk

- newrelic/hooks/datastore_aioredis.py
- newrelic/hooks/datastore_redis.py
* Instrument calls to `waitaof` for redis clients.
* Fix logic for aioredis `instance_info()`
> Instrument Redis waitaof

- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_prediction_stats.py
- tox.ini
* Swap custom metrics for dimensional metrics in SKLearn instrumentation.
* Adjust variable naming in SKLearn instrumentation to match PEP8.
> Use Dimensional Metrics in SKLearn

- codecov.yml
This PR essentially is ignoring false negatives for coverage.  The functionality excluded is something that is tested but is not registered as being covered because it is called through the command line (a separate process).
> Exclude command line functionality from test coverage

- newrelic/core/otlp_utils.py
- tests/agent_features/test_dimensional_metrics.py
- tests/testing_support/validators/validate_dimensional_metric_payload.py
* Fix duplicate encoding of count metrics as summary metrics in OTLP.
* Includes regression test.
> Fix OTLP Count Metric Serialization

- tests/framework_starlette/test_bg_tasks.py
- tox.ini
* Starlette has once again fixed the long standing background task bug with BaseHTTPMiddleware as of v0.29.0. Tests updated to reflect this change in behavior.
> Fix Starlette Testing Matrix for Updated Behavior

- newrelic/api/transaction.py
- tests/agent_features/test_distributed_tracing.py
- tests/agent_features/test_serverless_mode.py
* The spec for Serverless Distributed Tracing outlines that `trusted_account_key` need not be set in Serverless environments, and should fall back to the use of `account_id` in all use cases instead.
* Fix issue by adding fallback lookups under serverless mode.
* Add testing to serverless mode DT tests for this logic.
* Add testing to regular DT tests that verifies this ONLY applies in Serverless mode.
> Correct Serverless Distributed Tracing Logic

- .github/containers/Dockerfile
- tox.ini
This PR does several things:
1. Adds the typing-extensions package as a dependency for uvicorn
2. Adds the full version of pypy3.8 to the Docker container setup.  This fix does not break the existing script that is setup to find the latest install of the specified Python version
3. Removes solrpy from tests (this framework was last released May 12, 2020 and is (at the time of this PR creation) outside New Relic's support window)
> Add full version for pypy3.8 to tox

- newrelic/config.py
- newrelic/hooks/datastore_aioredis.py
- newrelic/hooks/datastore_redis.py
- tox.ini
This PR will add a new instrumentation for redis.asyncio.client and remove aioredis' intrumentation dependency
Closes the issue https://github.com/newrelic/newrelic-python-agent/issues/807
> Added separate instrumentation for redis.asyncio.client

- .github/workflows/tests.yml
- newrelic/config.py
- newrelic/hooks/datastore_redis.py
- setup.cfg
- tests/datastore_rediscluster/conftest.py
- tests/datastore_rediscluster/test_uninstrumented_rediscluster_methods.py
- tests/testing_support/db_settings.py
- tox.ini
RedisCluster was added in ~2021 and is a new client that we need to instrument. Because we chose to instrument at a higher level, when RedisCluster was added it inherited commands from lower level classes below our instrumentation and we missed it.
> Instrument RedisCluster

- newrelic/config.py
- newrelic/hooks/datastore_firestore.py
- tests/datastore_firestore/test_collections.py
- tests/datastore_firestore/test_documents.py
* Remove unnecessary Firestore hooks.
* Clean up Firestore instrumentation to more readable approach.
> Refactor Firestore Hooks

- .github/containers/Dockerfile
- .github/workflows/tests.yml
- newrelic/hooks/mlmodel_sklearn.py
- tests/mlmodel_sklearn/test_inference_events.py
- tests/mlmodel_sklearn/test_ml_model.py
- tox.ini
1. This changes from sending 1 event per feature/label value to 1 event per prediction (Also referred to as a change in "schema").
* Replace feature_name & feature_value and label_name & label_value to `feature.<name> = <value>` and `label.<name> = <value>`.
* Remove feature_type and label_type.
* Add a new schema attribute.
1. Remove pypy38 from test suite and remove compile dependencies from Dockerfile. Scipy wasn't able to compile consistently regardless of installing the necessary dependencies and adding these extra dependencies broke the kafka compile.
> Only send 1 event per prediction & fix tests

- tests/agent_features/test_span_events.py
- tests/datastore_postgresql/conftest.py
- tests/datastore_postgresql/test_database.py
This PR adds a "WITH..." query to postgresql tests in order to test the "other" category in Postgres query types.
> Modify postgresql tests to include WITH query

- newrelic/api/datastore_trace.py
- tests/agent_features/test_datastore_trace.py
- tests/testing_support/validators/validate_datastore_trace_inputs.py
This PR updates the `datastore_trace` wrapper to take in `host`, `port_path_or_id`, and `database_name`.
> Update datastore_trace wrapper to take instance info

- newrelic/api/database_trace.py
- newrelic/api/datastore_trace.py
- newrelic/api/external_trace.py
- newrelic/api/function_trace.py
- newrelic/api/graphql_trace.py
- newrelic/api/memcache_trace.py
- newrelic/api/message_trace.py
- tests/agent_features/test_async_wrapper_detection.py
* Add `async_wrapper` as an argument to all trace APIs to allow manual overrides of the async wrapper when introspection is not possible, but the return type is known.
* Includes tests on a generator, and generator obscured by a wrapper function.
> Trace Async Wrapper Argument

- newrelic/common/async_wrapper.py
- tests/agent_features/_test_async_generator_trace.py
- tests/agent_features/test_coroutine_trace.py
* Fix implementation of generator wrappers to be more robust.
* Add regression testing for bugs in generator wrappers.
> Fix Generator Wrappers

- newrelic/common/agent_http.py
- tests/agent_unittests/test_agent_protocol.py
- tests/agent_unittests/test_http_client.py
Fix an issue in the certificate fallback logic. Only use fallback NR certificates if both the ca file and ca path are None.
This fixes https://github.com/newrelic/newrelic-python-agent/issues/906.
> Add check for both path and file

- tox.ini
This PR pins framework_starlette: anyio to < v4.0.0
`anyio` is used for `test_exception_in_middleware` test in Starlette: https://github.com/encode/starlette/pull/1157
However, v4.0.0 of `anyio` creates breaking changes to our tests (but not the instrumentation): https://github.com/agronholm/anyio/releases/tag/4.0.0
This should be kept in our tests until Starlette v0.17.0 is no longer within New Relic's support window (January 23, 2024)
> Pin anyio version to below 4.0.0

- newrelic/config.py
- newrelic/hooks/datastore_redis.py
- newrelic/hooks/framework_flask.py
- tests/datastore_redis/test_asyncio.py
- tox.ini
This PR 
- Adds instrumentation for redis.asyncio.Connection
- Drops Flask support for Python 2.7 since the last version of Flask to support Python 2.7 (v1.1.2) is outside New Relic's supportability window (Since April 2022)
> Add redis.asyncio.Connection instrumentation

- newrelic/agent.py
This PR adds `wrap_mlmodel` to the `newrelic.agent` package for public use.
> Expose wrap_mlmodel as public API

- .github/containers/install-python.sh
- newrelic/hooks/framework_bottle.py
- newrelic/hooks/framework_pyramid.py
- newrelic/hooks/logger_loguru.py
- newrelic/hooks/messagebroker_pika.py
- tests/datastore_redis/test_custom_conn_pool.py
- tests/datastore_redis/test_execute_command.py
- tests/datastore_redis/test_get_and_set.py
- tests/datastore_redis/test_multiple_dbs.py
- tests/datastore_redis/test_rb.py
- tox.ini
* Fix merge conflicts for develop scikitlearn branch.
> Fix merge conflicts for develop scikitlearn

- newrelic/core/config.py
This PR disables `machine_learning.inference_events_value.enabled` by default.
> Disable ML inference events capture by default.

- tox.ini
This PR pins the flask version being installed for flask-restx tests until v3 support is added: https://github.com/python-restx/flask-restx/pull/572
> Pin flask version for flask restx tests.

- newrelic/hooks/mlmodel_openai.py
- tests/mlmodel_openai/conftest.py
- tests/mlmodel_openai/test_chat_completion.py
- tests/mlmodel_openai/test_embeddings.py
Instrument `Embedding.acreate` and `ChatCompletion.acreate` for open ai.
> Instrument acreate's for open-ai

- newrelic/common/package_version_utils.py
- tests/agent_unittests/test_package_version_utils.py
* Implement caching for package version lookups to prevent future performance issues.
* Note: Python 2.7 does not support this decorator and requires a custom implementation of caching. The implementation closely mirrors `@functools.cache` including thread safety and the `cache_clear()` function.
Supersedes and closes #817
> Cache Package Version Lookups

- .github/actions/update-rpm-config/action.yml
- .github/workflows/deploy-python.yml
- .github/workflows/tests.yml
- newrelic/common/package_version_utils.py
- newrelic/hooks/datastore_redis.py
- tests/agent_unittests/test_package_version_utils.py
- tests/datastore_redis/conftest.py
- tests/datastore_redis/test_generators.py
- tests/datastore_redis/test_uninstrumented_methods.py
- tests/mlmodel_bedrock/_mock_external_bedrock_server.py
- tests/mlmodel_bedrock/conftest.py
- tests/mlmodel_bedrock/test_chat_completion.py
- tox.ini
* Add testing infrastructure for AWS Bedrock to tox.
* Add base files for test suite
* Includes a simple no harm test for 4 text based models, and recorded responses.
* Add record/replay server for Bedrock
* Move OpenAI record/replay server to test suite folder and out of testing_support
* The files were not general enough to exactly reuse, had to implement new logic for parsing prompts and headers from objects and payloads.
* Change recording for OpenAI/Bedrock to use json printer
* pprint looks nice, but was getting in the way with splitting strings on long lines.
* This now records `None` as `null` which is annoying but can be fixed with a find/replace.
> Bedrock Testing Infrastructure

- tests/mlmodel_openai/_mock_external_openai_server.py
- tests/mlmodel_openai/conftest.py
- tests/mlmodel_openai/test_error.py
Add ability to record and mock error responses from open ai server.
> Mock openai error responses

- tox.ini
Hypercorn released [version 0.15](https://github.com/pgjones/hypercorn/releases/tag/0.15.0) which drops Python 3.7 support.  One non-backwards compatible change is that `Literal` is imported from `typing` which is only supported in Python 3.8+.  This PR removes testing for Python 3.7 in Hypercorn.
> Drop python 3.7 tests for Hypercorn

- newrelic/config.py
This PR removes a duplicate kafka import hook in newrelic/config.py
> Remove duplicate kafka import hook

- tests/framework_starlette/test_application.py
- tests/framework_starlette/test_bg_tasks.py
Fix parsing of unexpected non-int starlette release number in tests.
> Handle unexpected starlette version in tests

- newrelic/common/package_version_utils.py
- tests/agent_unittests/test_package_version_utils.py
* Fixes performance issues with `get_package_version` by reverting #878.
* Avoid reintroducing DeprecationWarnings by suppressing warnings when accessing package version attributes.
* Accessing these first for speed is intended behavior whether or not the version attribute is marked as deprecated. The agent is robust enough to handle the removal of these attributes, which makes the DeprecationWarnings irrelevant.
* Closes #927
* Closes #918
> Package Version Performance Regression

- newrelic/api/transaction.py
- newrelic/common/package_version_utils.py
- newrelic/config.py
- newrelic/core/application.py
- newrelic/core/config.py
- newrelic/core/custom_event.py
- tests/agent_features/test_custom_events.py
- tests/agent_unittests/test_package_version_utils.py
Merge increase custom event limit changes into ai-preview branch.
> Merge improved-record-ml-event into develop-ai-limited-preview

- .github/workflows/deploy-python.yml
* Removes accidental extra quote from workflow.
> Remove Extra Quote from API Keys

- newrelic/hooks/external_botocore.py
- newrelic/hooks/mlmodel_openai.py
- tests/external_botocore/test_bedrock_chat_completion.py
- tests/external_botocore/test_bedrock_embeddings.py
- tests/mlmodel_openai/test_chat_completion.py
- tests/mlmodel_openai/test_chat_completion_error.py
- tests/mlmodel_openai/test_embeddings.py
- tests/mlmodel_openai/test_embeddings_error.py
Use named function traces in OpenAI:
* `Llm/completion/OpenAI/<function name>`
* `Llm/embedding/OpenAI/<function name>`
Use named function traces in Bedrock:
* `Llm/completion/Bedrock/<function name>`
* `Llm/embedding/Bedrock/<function name>`
> Use named function traces

- newrelic/hooks/mlmodel_openai.py
Adds an early exit conditional for streaming so we don't try to instrument during streaming right now.
> Add early exit conditional for streaming

- newrelic/hooks/messagebroker_confluentkafka.py
- newrelic/hooks/messagebroker_kafkapython.py
- tests/messagebroker_confluentkafka/test_producer.py
- tests/messagebroker_kafkapython/test_producer.py
Only add headers if headers exist in MessageTrace
A fix for https://github.com/newrelic/newrelic-python-agent/issues/743
> Fix Kafka/Confluent Kafka header bug

- newrelic/hooks/external_botocore.py
- newrelic/hooks/mlmodel_openai.py
- tests/external_botocore/test_bedrock_chat_completion.py
- tests/mlmodel_openai/test_chat_completion.py
- tests/mlmodel_openai/test_chat_completion_error.py
- tests/mlmodel_openai/test_chat_completion_error_v1.py
- tests/mlmodel_openai/test_chat_completion_v1.py
- tests/mlmodel_openai/test_get_llm_message_ids.py
- tests/mlmodel_openai/test_get_llm_message_ids_v1.py
Expect conversation_id attribute to be `llm.conversation_id`.
> Prefix conversation id with llm

- newrelic/api/application.py
- newrelic/api/log.py
- newrelic/api/transaction.py
- newrelic/common/encoding_utils.py
- newrelic/config.py
- newrelic/core/agent.py
- newrelic/core/application.py
- newrelic/core/attribute.py
- newrelic/core/attribute_filter.py
- newrelic/core/config.py
- newrelic/core/stats_engine.py
- newrelic/hooks/logger_logging.py
- tests/agent_features/test_log_events.py
- tests/agent_features/test_logs_in_context.py
- tests/logger_logging/test_attribute_forwarding.py
- tests/logger_logging/test_logging_handler.py
- tests/logger_loguru/conftest.py
- tests/logger_loguru/test_attribute_forwarding.py
- tests/testing_support/validators/validate_log_event_count.py
- tests/testing_support/validators/validate_log_event_count_outside_transaction.py
- tests/testing_support/validators/validate_log_events.py
- tests/testing_support/validators/validate_log_events_outside_transaction.py
* Add filtering to context data from log events leveraging existing attribute system.
> Log Attribute Filtering

- tox.ini
This PR removes Python 2.7 from being tested with memcache since the library no longer supports it.
> Drop memcache py27 support.

- tox.ini
Temporarily pin hypercorn testing suite from latest to <0.16
> Temporarily pin hypercorn version in tests

- .github/workflows/deploy-python.yml
- tests/agent_unittests/test_package_version_utils.py
* Add parallelized build strategy for wheels to reduce build times.
* Add Python 3.12 wheels.
* Add mullinux wheels in addition to manylinux wheels.
* Add validation tests (agent_unittests) to end of wheel build process.
* Update actions used in build and deploy to newer versions.
> Parallel Wheel Builds

- CONTRIBUTING.rst
This PR removes the Slack workspace details present in the `CONTRIBUTING.rst` as the workspace is no longer active.  
Fixes #968
> Remove Slack section in CONTRIBUTING.rst.

- tests/external_botocore/test_boto3_iam.py
- tests/external_botocore/test_boto3_s3.py
- tests/external_botocore/test_boto3_sns.py
- tests/external_botocore/test_botocore_dynamodb.py
- tests/external_botocore/test_botocore_ec2.py
- tests/external_botocore/test_botocore_s3.py
- tests/external_botocore/test_botocore_sqs.py
- tox.ini
This PR updates the `moto` decorators used in `botocore` tests and removes py27 dependencies listed in `tox.ini`. It also drops testing for Python 3.7 since `botocore` no longer supports this version.
> Update botocore tests.

- tests/external_botocore/test_boto3_iam.py
- tests/external_botocore/test_boto3_s3.py
- tests/external_botocore/test_boto3_sns.py
- tests/external_botocore/test_botocore_dynamodb.py
- tests/external_botocore/test_botocore_ec2.py
- tests/external_botocore/test_botocore_s3.py
- tests/external_botocore/test_botocore_sqs.py
This PR removes moto imports for Python 3.7 since support for this version has been dropped.
> Remove imports for moto on py37.

- newrelic/hooks/mlmodel_langchain.py
- tests/external_botocore/test_boto3_iam.py
- tests/external_botocore/test_boto3_s3.py
- tests/external_botocore/test_boto3_sns.py
- tests/external_botocore/test_botocore_dynamodb.py
- tests/external_botocore/test_botocore_ec2.py
- tests/external_botocore/test_botocore_s3.py
- tests/external_botocore/test_botocore_sqs.py
- tests/mlmodel_langchain/test_vectorstore.py
- tox.ini
This PR adds error handling for Langchain's VectorStore.
> Langchain VectorStore error handling

- tox.ini
* Pin `pydantic-core` for PyPy 3.8 to last version with wheel support.
> Fix CherryPy PyPy 3.8 Tests by Pinning Pydantic

- tests/mlmodel_sklearn/test_cluster_models.py
- tests/mlmodel_sklearn/test_dummy_models.py
- tests/mlmodel_sklearn/test_ensemble_models.py
- tests/mlmodel_sklearn/test_feature_selection_models.py
- tests/mlmodel_sklearn/test_linear_models.py
- tests/mlmodel_sklearn/test_multioutput_models.py
- tests/mlmodel_sklearn/test_naive_bayes_models.py
- tests/mlmodel_sklearn/test_neighbors_models.py
- tests/mlmodel_sklearn/test_neural_network_models.py
- tests/mlmodel_sklearn/test_pipeline_models.py
- tests/mlmodel_sklearn/test_semi_supervised_models.py
- tests/mlmodel_sklearn/test_svm_models.py
Utilize the common parsing method that already handels non integer versions rather than building our own.
> Fix sklearn version tuple parsing in tests

- newrelic/api/transaction.py
- newrelic/core/attribute.py
- newrelic/core/node_mixin.py
- newrelic/core/root_node.py
- newrelic/core/stats_engine.py
- newrelic/core/transaction_node.py
- tests/agent_features/test_custom_events.py
- tests/agent_features/test_dimensional_metrics.py
- tests/agent_features/test_error_events.py
- tests/agent_features/test_log_events.py
- tests/agent_features/test_time_trace.py
- tests/agent_features/test_transaction_event_data_and_some_browser_stuff_too.py
- tests/logger_logging/test_attributes.py
- tests/logger_loguru/test_attributes.py
This PR attempts to align the Python agent with the agent spec by dropping attributes with a value of None.
According to the spec:
> Agents **SHOULD NOT** report `null` attribute values. The behavior of `IS NULL` queries in insights makes it so that omitted keys behave the same as `null` keys. Since there is no difference between omitting the key and sending a `null`, we **SHOULD** reduce the payload size by omitting `null` values from the payload entirely.
> Since there should not be a difference in behavior for customers recording `null` attributes versus customers omitting an attribute, agents **SHOULD** add debug logging when a null value is recorded. This will give agents observability on recording of `null` attributes outside of audit logs.
> "empty" values such as `""` and `0` …
> Drop attributes with a value of None

- newrelic/hooks/mlmodel_openai.py
- tests/mlmodel_langchain/_mock_external_openai_server.py
- tests/mlmodel_langchain/conftest.py
- tests/mlmodel_langchain/test_agent.py
- tests/mlmodel_openai/test_chat_completion_stream.py
- tests/mlmodel_openai/test_chat_completion_stream_v1.py
Previously, langchain agent tests were skipped because they were dependent on streaming instrumentation support which hadn't been implemented yet. Now we support streaming in openai so remove the skip condition and actually run these tests.
Note: this is dependent on #1068 which should be merged first.
> Run langchain agent tests

- newrelic/config.py
- newrelic/hooks/mlmodel_langchain.py
This PR adds Kinetica to the list of vectorstores instrumented in Langchain.
> Add Kinetica vectorstore to Langchain

- newrelic/api/log.py
- tests/agent_features/test_logs_in_context.py
In v9.5.0, a bug in the NewRelicContextFormatter was introduced where "message" was added to the default set of keys to exclude. This made the default key list (default keys + 1) in length. Since the logic check was based on the length, rather than presence of certain keys, anything that had one extra key than the default would not have that extra key added to the ouput because the length would match the (default keys + 1) length.
The length check that was previously used was a bit of an odd choice. Replace this with a check for keys not in the default keys list.
> Fix NewRelicContextFormatter bug

- newrelic/config.py
- newrelic/hooks/mlmodel_langchain.py
This PR adds InfinispanVS and DocumentDBVectorSearch to the list of vectorstores in Langchain
> Add new vectorstores to Langchain

- newrelic/config.py
- newrelic/core/config.py
- newrelic/hooks/external_botocore.py
- newrelic/hooks/mlmodel_langchain.py
- newrelic/hooks/mlmodel_openai.py
- tests/external_botocore/conftest.py
- tests/external_botocore/test_bedrock_chat_completion.py
- tests/external_botocore/test_bedrock_embeddings.py
- tests/mlmodel_langchain/conftest.py
- tests/mlmodel_langchain/test_chain.py
- tests/mlmodel_langchain/test_tool.py
- tests/mlmodel_langchain/test_vectorstore.py
- tests/mlmodel_openai/conftest.py
- tests/mlmodel_openai/test_chat_completion.py
- tests/mlmodel_openai/test_chat_completion_error.py
- tests/mlmodel_openai/test_chat_completion_error_v1.py
- tests/mlmodel_openai/test_chat_completion_stream.py
- tests/mlmodel_openai/test_chat_completion_stream_error.py
- tests/mlmodel_openai/test_chat_completion_stream_error_v1.py
- tests/mlmodel_openai/test_chat_completion_stream_v1.py
- tests/mlmodel_openai/test_chat_completion_v1.py
- tests/mlmodel_openai/test_embeddings.py
- tests/mlmodel_openai/test_embeddings_error.py
- tests/mlmodel_openai/test_embeddings_error_v1.py
- tests/mlmodel_openai/test_embeddings_v1.py
This PR adds the `ai_monitoring.record_content.enabled` flag, which obfuscates query content's input/outputs
> Add ai_monitoring.record_content.enabled flag

- tox.ini
Neither langchain nor openai list support for pypy so do not run tests for them on a pypy env.
> Remove pypy310 test envs from openai & langchain

- newrelic/hooks/mlmodel_openai.py
- tests/mlmodel_openai/conftest.py
- tests/mlmodel_openai/test_embeddings_stream_v1.py
Add early exit condition to not wrap embedding streaming in openai v1. It appears that streaming for embeddings isn't support in openai v0 though I'm keeping the early exit condition for that in place just in case.
Note no mocked response was added specifically for streamed embeddings. This is because the response in streamed vs unstreamed is the same format, it just sends the data in chunks instead of all at once. In other words: the non-streamed mock response will also work when mocking streaming mode.
> Test embedding streaming openai v1

- newrelic/hooks/mlmodel_openai.py
To reproduce:
```
import newrelic.agent
@newrelic.agent.background_task()
def streamingOpenAI(prompt):
import openai
print(f'prompt with openai: {prompt}')
response = openai.chat.completions.create(
model='gpt-3.5-turbo',
messages=[
{'role': 'user', 'content': prompt}
],
temperature=0,
stream=True,
)
message = ""
i = 1
for chunk in response:
if 'choices' in chunk:
i+=1
for choice in chunk['choices']:
if 'delta' in choice and 'content' in choice['delta']:
message += choice['delta']['content']
print(f'output ({i}): {message}\n\n')
if __name__ == "__main__":
newrelic.agent.initialize('newrelic.ini')
newrelic.agent.register_application(timeout=10)
prompt = "What is 2 + 2?"
streamingOpenAI(prompt)
newrelic.agent.shutdown_agent(60)
print("Agent run finished!")
```
When you click on the AI …
> Fix openai streaming wrong span bug

- newrelic/bootstrap/sitecustomize.py
- newrelic/config.py
- newrelic/core/config.py
- newrelic/hooks/application_celery.py
- tests/application_celery/_target_application.py
- tests/application_celery/conftest.py
- tests/application_celery/test_application.py
- tests/application_celery/test_distributed_tracing.py
- tests/application_celery/test_max_tasks_per_child.py
- tests/application_celery/test_task_methods.py
- tox.ini
Add a configuration setting to indicate that the agent is being injected by the Kubernetes Agent Operator and that we should skip the python version safety check in sitecustomize.
See agent spec for details (open PR).
> Add NEW_RELIC_K8S_OPERATOR_ENABLED

- tox.ini
Jinja no longer supports Python 3.7 since April 23rd, so we are dropping it from being tested against the latest version.
> Drop Python 3.7 for jinja testing

- newrelic/hooks/external_urllib3.py
- tests/external_urllib3/test_urllib3.py
This PR explicitly adds `http.method` to urllib3 traces
> Add method to urllib3 trace

- newrelic/hooks/framework_grpc.py
* gRPC detection was picking up a new `dns:///` prefix, stripping this before reporting the URI.
> Fix gRPC URI Detection

- newrelic/bootstrap/sitecustomize.py
* Add section to sitecustomize to support initializing using the K8s agents operator.
* Refactor sitecustomize logic to fix several crashes and inconsistencies around imports.
> K8s sitecustomize changes

- newrelic/hooks/external_botocore.py
llama3 is the same parsing as llama2 so just drop the number from the key to support both.
> Add support for llama3

- newrelic/hooks/mlmodel_openai.py
Pop needs a default value, otherwise it will raise an exception if the key is not found.
> Add default to pop to guard against key not found

- tests/mlmodel_sklearn/test_ensemble_models.py
This PR updates the expected metrics for sklearn's `HistGradientBoostingClassifier`. In v1.5.0, calls to `predict_proba` [were removed](https://github.com/scikit-learn/scikit-learn/pull/27844) for performance reasons.
> Fix sklearn ensemble tests.

- newrelic/hooks/external_botocore.py
- newrelic/hooks/mlmodel_langchain.py
- newrelic/hooks/mlmodel_openai.py
In order to match behavior across agents, the python agent should report the `duration` field on AI Monitoring events in milliseconds rather than seconds.
The test suite does not currently check the `duration` field because the integration tests have variability between runs
> Fix LLM event durations

- newrelic/api/asgi_application.py
- tests/agent_features/test_asgi_browser.py
Previously, if there was no content length header and browser injection was enabled, the ASGI wrapper would fail with a TypeError as the header_value would be None. Now, the except clause catches both type and value errors.
Fixes #1150.
> Fix bug in ASGI when no content-length header

- tests/framework_flask/_test_blueprints.py
- tests/framework_flask/_test_middleware.py
- tests/framework_flask/conftest.py
- tests/framework_flask/test_blueprints.py
- tests/framework_flask/test_middleware.py
- tox.ini
This PR enables the testing of flaskmaster (pulls repo from main branch as well as latest) as well as updating Flask tests.  More information found here on why extras were installed separately from archive: https://github.com/pypa/pip/pull/11617
Because jinja2 was pinned to v3.0.3, flasklatest was actually installing Flask v2.1.3 (which is still compatible with that version of jinja2) instead of the actual latest version.
> Update flask tests and enable flaskmaster

- newrelic/core/environment.py
* Fix the following error where the name `version` could be unbound.
```
File "/__w/newrelic-python-agent/newrelic-python-agent/.tox/python-agent_unittests-py27-with_extensions/lib/python2.7/site-packages/newrelic/core/environment.py", line 246, in environment_settings
if version or nr_hook:
UnboundLocalError: local variable 'version' referenced before assignment
```
> Fix Environment Scraping Logic

- newrelic/config.py
- newrelic/hooks/datastore_aiomcache.py
- tests/datastore_aiomcache/conftest.py
- tests/datastore_aiomcache/test_aiomcache.py
- tox.ini
Adds support to [aiomcache](https://github.com/aio-libs/aiomcache/) instrumentation.
For most contributions it is strongly recommended to add additional tests …
> Adds instrumentation for aiomcache

- newrelic/hooks/mlmodel_langchain.py
- tests/mlmodel_langchain/test_agent.py
- tests/mlmodel_langchain/test_chain.py
- tests/mlmodel_langchain/test_tool.py
- tests/mlmodel_langchain/test_vectorstore.py
Previously, when using langchain only (no bedrock or openai), the metric name was not correct so the AI tab would not show up. This has been fixed.
> Change Langchain->LangChain per agent spec

- newrelic/api/log.py
- tests/agent_features/test_logs_in_context.py
Currently the `NewRelicContextFormatter` implementation doesn't support including the stack trace. It would be convenient if there was an option because it would allow stack frames to be included as an attribute for an log in NR (instead of them being broken up by frame, which is the default if structured logs are not used). This PR is adding opt-in support for including stack traces.
https://github.com/newrelic/newrelic-python-agent/issues/1169
> NewRelicContextFormatter update to support adding a stack trace

- newrelic/api/message_trace.py
- newrelic/core/attribute.py
- newrelic/hooks/external_botocore.py
- tests/external_botocore/test_botocore_sqs.py
Capture AWS SQS agent attributes on message spans.
> Capture AWS SQS info on message spans

- tests/framework_aiohttp/test_client_cat.py
Fix failing aiohttp tests by moving the connector instantiation inside event loop.
> Move connector instantiation inside event loop

- newrelic/config.py
- newrelic/hooks/external_botocore.py
- newrelic/hooks/external_s3transfer.py
- tests/external_botocore/_test_file.txt
- tests/external_botocore/test_boto3_s3.py
- tests/external_botocore/test_s3transfer.py
This PR instruments the Instrument s3transfer BoundExecutor submit function. This supports context propagation so that the agent is able to instrument `upload_file` in boto3.
Closes #1178.
> Instrument s3transfer BoundExecutor submit function. 

- newrelic/api/message_trace.py
Fix bug where params aren't getting passed into MessageTrace call.
> Fix params not getting passed bug

- newrelic/core/config.py
This PR adds an env var for the setting to control whether GC runtime metrics are enabled.
> Add env var for GC runtime metrics.

- newrelic/hooks/framework_grpc.py
- tests/framework_grpc/test_get_url.py
lstrip strips all the characters from the beginning of the string so strings that begin in d, n, or s get the first character(s) stripped. Replace is actually what we want in this case.
> Use replace instead of lstrip to strip dns://

- newrelic/core/environment.py
- tests/agent_unittests/test_environment.py
`uvicorn.workers` has been moved to a separate package called `uvicorn_worker`. Check for both names of this module when reporting dispatcher information.
Discovered thanks to issue #1208.
Unrelated to the problem that issue reported however.
> Add Dispatcher Information for uvicorn-worker Package

- tests/external_botocore/test_bedrock_chat_completion.py
- tests/mlmodel_langchain/test_chain.py
- tests/mlmodel_langchain/test_tool.py
- tox.ini
Fix the following AI test failures:
* Bedrock changed the order of payload assertions in commit: https://github.com/boto/botocore/commit/db41663ea2fa84cb77d548934c92d3d5c26c2c05 which resulted in the expected error being different due to the validator order change.
* Langchain added metadata to Document interface so update expected events with this field.
* pydantic ValidationError moved locations so adjust the path to the error in the tests.
* Langchain doesn't list support for Python3.8 so do not test it on Python3.8.
* Graphql main tests are failing so comment these out for now.
> Fix AI test failures & do not run graphqlmaster tests

- newrelic/hooks/messagebroker_kafkapython.py
- tox.ini
[kafka-python](https://github.com/dpkp/kafka-python) has moved to [kafka-python-ng](https://github.com/wbarnha/kafka-python-ng/) due to lack of response from the original maintainer of the package.
> Add support for kafka-python-ng

- newrelic/hooks/datastore_aiomcache.py
- newrelic/hooks/datastore_bmemcached.py
- newrelic/hooks/datastore_pymemcache.py
- tests/datastore_aiomcache/test_aiomcache.py
- tests/datastore_bmemcached/test_memcache.py
- tests/datastore_pymemcache/test_memcache.py
Capture host & port to create AWS entity metric on bmemcached, aiomcache, and pymemcache libraries.
Do not capture host and port info for no longer supported libraries umemcached (doesn't support Python3).
> Capture memcache host & port

- newrelic/hooks/messagebroker_confluentkafka.py
- newrelic/hooks/messagebroker_kafkapython.py
- tests/messagebroker_confluentkafka/conftest.py
- tests/messagebroker_confluentkafka/test_consumer.py
- tests/messagebroker_confluentkafka/test_producer.py
- tests/messagebroker_kafkapython/conftest.py
- tests/messagebroker_kafkapython/test_consumer.py
- tests/messagebroker_kafkapython/test_producer.py
Add bootstrap server metric for Kafka to connect MSK AWS entities.
> Add bootstrap server metric for kafka

- setup.py
* Add python version specific errors that recommend past agent versions when installing on an unsupported Python version.
`RuntimeError: The New Relic Python agent only supports Python 3.7+. We recommend upgrading to a newer version of Python. The last agent version to support Python 2.7 was v9.13.0.`
`RuntimeError: The New Relic Python agent only supports Python 3.7+. We recommend upgrading to a newer version of Python. The last agent version to support Python 3.6 was v7.16.0.178.`
> Add Python Version Specific Installation Errors

- newrelic/hooks/logger_loguru.py
- tests/logger_loguru/test_local_decorating.py
- tests/logger_loguru/test_log_forwarding.py
- tests/logger_loguru/test_metrics.py
- tests/logger_loguru/test_settings.py
- tox.ini
Remove versioned logic in loguru instrumentation as per agent support window.
> Remove versioned logic in loguru instrumentation 

- .github/workflows/deploy-python.yml
- newrelic/common/_monotonic.c
- newrelic/core/_thread_utilization.c
- setup.py
- tests/agent_unittests/test_full_uri_payloads.py
- tests/datastore_aiomcache/test_aiomcache.py
- tests/datastore_bmemcached/test_memcache.py
- tests/datastore_pymemcache/test_memcache.py
- tox.ini
* Add wheels and classifiers for Python 3.13.
* Update cibuildwheel to use a version with Python 3.13 support.
* Add support for setuptools_scm v7 & v8 for Python 3.13 compatibility.
* Add Python 3.13 to all relevant tox matrices.
* Add annotated and commented out environments where Python 3.13 is not yet supported by the library. Can be uncommented again to test in the next few weeks as more wheels become available, and should eventually be slotted into the existing matrix line.
* Update C Extensions to work with Python 3.13, and remove Python 2 macros.
* Fix broken tests for agent_unittests in developer mode.
* Fix broken metric across all memcache tests expecting too strict a localhost hostname.
> Python 3.13 Support

- .github/workflows/deploy-python.yml
* Python 3.7 doesn't support newer versions of `OpenSSL>1.1`, which `pypa/cibuildwheel` now uses.
* Build Python 3.7 wheels on a separate job using an older version of `pypa/cibuildwheel`
> Separate Python 3.7 Build Workflow

- newrelic/packages/urllib3/LICENSE.txt
The LICENSE.txt file was accidentally removed in a previous PR that upgraded urllib3.
> Add urllib3 LICENSE.txt file

- tox.ini
The [latest release of gRPC](https://github.com/grpc/grpc/releases/tag/v1.67.0) does not support Python 3.7 ([as seen here](https://github.com/grpc/grpc/pull/37643))
> Pin gRPC version supported in Python 3.7

- tox.ini
This PR temporarily disables flaskmaster tests for Python 3.8
> Disable flaskmaster-py38

- .github/workflows/tests.yml
- tests/adapter_daphne/test_daphne.py
- tests/adapter_hypercorn/test_hypercorn.py
- tox.ini
* Add tests to Daphne that exercise the HTTP/2 server capabilities.
* Identical to the tests for Hypercorn.
> Daphne HTTP/2 Testing

- newrelic/config.py
- newrelic/core/config.py
- tests/agent_features/test_configuration.py
Add cloud.aws.account_id configuration setting. This is not used in this PR but will be used in future AWS linking for the user to provide the account_id when it cannot be derived by the instrumentation. See the Entity-Relationships agent spec.
> Add cloud.aws.account_id config setting

- newrelic/config.py
- tests/agent_features/test_configuration.py
* Fixes bug where only str is accepted by `newrelic.initialize()` after update and not all `pathlib.Pathlike` object types (`str`, `bytes`, `PosixPath`, etc.).
Fixes #1267
> Fix Pathlike objects not accepted by newrelic.initialize()

- newrelic/config.py
- newrelic/hooks/database_aiomysql.py
- tests/datastore_aiomysql/conftest.py
- tests/datastore_aiomysql/test_database.py
- tox.ini
* Add instrumentation and tests for aiomysql.
> aiomysql Instrumentation

- .github/mergify.yml
* Disables mergify merge queue (replaced by GitHub's own merge queue)
* Updates mergify config 
* Closes #1264
> Disable Mergify Queue

- .gitignore
- newrelic/api/llm_custom_attributes.py
- pyproject.toml
- setup.py
- tests/cross_agent/test_ecs_data.py
- tests/datastore_motor/test_collection.py
- tests/datastore_pymongo/test_async_collection.py
- tests/datastore_pymongo/test_collection.py
* Add `.gitignore` entry for `pre-commit` config file
* Update configuration for various linters
* Add `flynt` configuration to `pyproject.toml`
* Run `flynt` against repo to fix more fstrings
> Chore - Update Linter Configs

- newrelic/config.py
- newrelic/hooks/mlmodel_langchain.py
This PR adds the TablestoreVectorStore to the list of VectorStores to be instrumented by LangChain
> Add Tablestore VectorStore

- newrelic/hooks/framework_starlette.py
After [Starlette v0.45.0](https://github.com/encode/starlette/releases/tag/0.45.0) the import proxy for `ExceptionMiddleware` was removed from `starlette.exceptions` (and now only resides in `starlette.middleware.exceptions`).  
This PR adds an additional checker to make sure that, when checking for double instrumentation, the import proxy exists (which is when this particular issue would occur).
> Check for ExceptionMiddlware removal in starlette.exceptions

- tox.ini
* Newer versions of sanic are incompatible with Python <=3.8 due to syntax errors. Pin older Python tests to the last supported sanic version.
> Fix Sanic Testing

- tests/mlmodel_langchain/test_vectorstore.py
This PR adds `metadata.page_label` search result to the vectorstore events tests
> Add additional metadata to vectorstore results

- newrelic/config.py
- newrelic/core/agent_control_health.py
- tests/agent_features/test_agent_control_health_check.py
This PR adds a new status code to the agent that sets health check reporting to unhealthy when a user has configured more than 3 app names.
> Add max three app name status for agent control health check

- newrelic/hooks/logger_structlog.py
- tests/logger_structlog/test_processor_formatter.py
This PR provides [a fix](https://github.com/newrelic/newrelic-python-agent/issues/1284) for the case where structlog's [ProcessorFormatter](https://www.structlog.org/en/stable/api.html#structlog.stdlib.ProcessorFormatter) is used as a [logging.Formatter](https://docs.python.org/3/library/logging.html#logging.Formatter) for both logging as well as structlog log entries.
For more information about this functionality: https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging
> Structlog processor formatter

- newrelic/api/log.py
- tests/agent_features/test_logs_in_context.py
`NewRelicContextFormatter` logs stack traces without causes which makes many errors hard to debug.
Let's take a look at the following code:
```python
try:
try:
raise ValueError("First exception")
except:
raise ValueError("Second exception")
except Exception as e:
logging.error("Encountered error", exc_info=e)
```
Before the PR, the exception message looked as follows:
```
File ".../newrelic_exception_cause.py", line 60, in <module>
raise ValueError("Second exception")
```
After the PR, it shows more details on the first cause:
```
Traceback (most recent call last):
File ".../newrelic_exception_cause.py", line 58, in <module>
raise ValueError("First exception")
ValueError: First exception
During handling of the above exception, another exception occurred:
Traceback (most recent call last): …
```
> fix(NewRelicContextFormatter): add cause and context to stack traces

- newrelic/config.py
- newrelic/hooks/mlmodel_langchain.py
- scripts/new_vectorstore_adder.py
- tests/mlmodel_langchain/new_vectorstore_adder.py
- tests/mlmodel_langchain/test_vectorstore.py
This PR adds a new LangChain Vectorstore instrumentation populator to the `scripts` directory as well as some tweaks to the existing instrumentation.
> Add Vectorstore instrumentation automation

- .github/workflows/build-ci-image.yml
- .github/workflows/deploy-python.yml
- .github/workflows/mega-linter.yml
- .github/workflows/tests.yml
* Pin all GHA runners to `ubuntu-22.04`
* Disable `fail-fast` strategy for deployment jobs.
> Rollback to Ubuntu-22 Runners

- .github/workflows/deploy-python.yml
Previously the workflow was using GITHUB_REF which is `refs/heads/tag-name` instead of `tag-name`. This has been fixed.
> Use name instead of ref

- newrelic/hooks/external_botocore.py
- tests/external_botocore/test_boto3_kinesis.py
Add aws entity support for Kinesis.
> Add aws entity support for Kinesis

- newrelic/hooks/external_botocore.py
- tests/external_botocore/test_boto3_firehose.py
- tests/external_botocore/test_boto3_kinesis.py
- tests/external_botocore/test_s3transfer.py
- tox.ini
* Add instrumentation and tests for AWS Firehose.
* Correct AWS Kinesis Instrumentation naming when no stream target is present.
* Tweak boto3/botocore in tox file.
* Fix S3Transfer test missing absolute path.
Currently depends on #1283 but will be rebased.
> AWS Kinesis Delivery Streams (Firehose) Entity Mapping

- newrelic/config.py
- newrelic/hooks/external_aiobotocore.py
- newrelic/hooks/external_botocore.py
- tests/external_aiobotocore/conftest.py
- tests/external_aiobotocore/test_bedrock_chat_completion.py
- tests/external_aiobotocore/test_bedrock_embeddings.py
- tests/external_botocore/_mock_external_bedrock_server.py
- tox.ini
This PR adds instrumentation and tests to support `invoke_model_with_response_stream` in async Bedrock.
> Add support for streaming in async Bedrock

- newrelic/config.py
- newrelic/hooks/external_aiobotocore.py
- newrelic/hooks/external_botocore.py
- tests/external_aiobotocore/conftest.py
- tests/external_aiobotocore/test_bedrock_chat_completion.py
- tests/external_aiobotocore/test_bedrock_embeddings.py
- tests/external_botocore/_mock_external_bedrock_server.py
- tox.ini
This PR adds instrumentation (non-streaming) to support async calls to Bedrock's `invoke_model` via `aioboto3` clients.
> Add Async Bedrock Instrumentation

- .github/workflows/deploy-python.yml
Pin setuptools to address breaking changes introduced in v71.0.0.
> Pin setuptools to v70.x.x.

- .devcontainer/devcontainer.json
- .github/containers/Dockerfile
* Add missing libs for building `mysqlclient` in CI.
* Update renamed feature in `devcontainer.json`
Build is here https://github.com/newrelic/newrelic-python-agent/actions/runs/14043517773
> Add Missing MySQL Libs to CI Container

- .github/workflows/deploy-python.yml
* Prevent race condition in publish steps by giving PyPi time to propagate the new release through the CDN.
> Add Wait on Publish Before Triggering Additional Workflows

- newrelic/hooks/messagebroker_kombu.py
The instrumentation for Kombu was missing an import of the global settings, causing a crash.
> Fix Kombu instrumentation import

- tests/cross_agent/test_docker_container_id.py
- tests/cross_agent/test_docker_container_id_v2.py
- tests/mlmodel_langchain/test_chain.py
- tests/mlmodel_langchain/test_tool.py
- tox.ini
Removes mock package dependency
> Removes mock package dependency

- newrelic/hooks/mlmodel_langchain.py
- tests/mlmodel_langchain/_mock_external_openai_server.py
- tests/mlmodel_langchain/test_chain.py
Fix issue with Langchain where response is type string and only the first character is captured.
> Support str response type in Langchain

- newrelic/config.py
- newrelic/hooks/mlmodel_gemini.py
- tests/mlmodel_gemini/test_embeddings.py
- tests/mlmodel_gemini/test_embeddings_error.py
- tests/testing_support/ml_testing_utils.py
This PR adds instrumentation + tests for sync and async embeddings in `google-genai`.
> Add Gemini Embeddings

- newrelic/core/database_node.py
- newrelic/core/datastore_node.py
- newrelic/core/node_mixin.py
- newrelic/hooks/external_botocore.py
- tests/agent_features/test_span_events.py
* Correct attributes on datastore spans to match spec.
* Add additional testing to validate the new attributes are attached, and properly truncated.
> Fix Datastore Span Attributes

- newrelic/admin/run_python.py
- newrelic/api/background_task.py
- newrelic/api/message_transaction.py
- newrelic/api/web_transaction.py
- newrelic/api/wsgi_application.py
- newrelic/common/utilization.py
- newrelic/console.py
- newrelic/core/config.py
- newrelic/core/internal_metrics.py
- newrelic/core/stack_trace.py
- newrelic/core/string_table.py
- newrelic/hooks/datastore_firestore.py
- newrelic/hooks/external_botocore.py
- newrelic/hooks/external_httpx.py
- pyproject.toml
- tests/adapter_gunicorn/test_aiohttp_app_factory.py
- tests/datastore_psycopg2/test_async.py
- tests/datastore_sqlite/test_database.py
- tests/framework_django/test_asgi_application.py
- tests/testing_support/fixtures.py
* Enable `pycodestyle` E(rror) rules.
* Temporarily disable bare-except rule (`except:` instead of `except Exception:`).
* Will require a separate effort to track down the intended behavior of each of these, and add `BaseException` or `Exception` depending.
* Disable line-too-long rule, as line length is handled by `ruff format`.
* Fix all other violations.
> Enable pycodestyle

- .gitignore
- .pre-commit-config.yaml
* Adds a default `pre-commit` config file, with `ruff` and `addlicense` hooks set to `pre-push`.
* Using this file is entirely optional, and includes instructions for editing the defaults.
> Add pre-commit Hooks

- newrelic/config.py
`instrumentation.graphql.capture_introspection_queries` should be configurable through the `*.ini` file as well as the `NEW_RELIC_INSTRUMENTATION_GRAPHQL_CAPTURE_INTROSPECTION_QUERIES` environment variable, but it was missing from the `newrelic/config.py` settings declaration.
> Enable instrospection_queries config setting

- .devcontainer/Dockerfile
- .github/LICENSE_HEADER
- .github/containers/Dockerfile
- .github/dependabot.yml
- .github/mergify.yml
- .github/workflows/addlicense.yml
- .github/workflows/mega-linter.yml
- .mega-linter.yml
- codecov.yml
- newrelic/core/infinite_tracing.proto
- newrelic/hooks/component_graphqlserver.py
- newrelic/hooks/datastore_aiomcache.py
- pyproject.toml
- tests/cross_agent/fixtures/ecs_container_id/ecs_mock_server.py
- tests/mlmodel_langchain/new_vectorstore_adder.py
* Add `google/addlicense` license header linter to CI image.
* Unavailable in Megalinter, and the pre-built docker image is a bit too restrictive with no shell.
* Add GHA job to check license headers.
* Fix all files missing license headers.
* Working test run with dev CI image [here](https://github.com/newrelic/newrelic-python-agent/actions/runs/14605392744/job/40973183282?pr=1357).
> License Header Linter

- .github/containers/Dockerfile
* Fixes string quoting in odbc sed command in Dockerfile.
Verified new contents of affected file by hand following rebuild on both platforms.
```
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=/usr/lib/x86_64-linux-gnu/odbc/psqlodbca.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=/usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
```
```
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=/usr/lib/aarch64-linux-gnu/odbc/psqlodbca.so
Setup=/usr/lib/aarch64-linux-gnu/odbc/libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
[PostgreSQL Unicode] …
```
> Fix odbc Dockerfile Error

- .github/dependabot.yml
- .github/workflows/addlicense.yml
- .github/workflows/build-ci-image.yml
- .github/workflows/deploy-python.yml
- .github/workflows/mega-linter.yml
- .github/workflows/tests.yml
- .github/workflows/trivy.yml
* Updates all actions (besides pinned Python 3.7 builder) to latest versions.
* Pins sha for `github/codeql-action/upload-sarif@v3` to `45775bd8235c68ba998cffa5171334d58593da47 # 3.28.15`.
* Configure dependabot to group PRs for all actions besides `cibuildwheel` for the future.
> Update All GitHub Action Versions

- .github/workflows/deploy-python.yml
- .github/workflows/tests.yml
* Fix coverage upload by enabling `include-hidden-files: true` on `actions/upload-artifact`
* Include `if-no-files-found: error` to prevent future issues.
> Enable hidden file uploads for coverage

- .github/dependabot.yml
* Adds ignore logic to dependabot to avoid updating pinned cibuildwheel version for Python 3.7.
> Dependabot Ignore Pinned cibuildwheel Version

- .github/workflows/tests.yml
* Fix tests job status check setting to skipped on a test failure rather than failure.
Example workflow runs:
* [Cancelled](https://github.com/newrelic/newrelic-python-agent/actions/runs/14784891316/job/41511479416?pr=1381)
* [Failure](https://github.com/newrelic/newrelic-python-agent/actions/runs/14784895255/job/41511806059?pr=1381)
* Success (Current run)
> Fix Tests Workflow Status

- tox.ini
* `pymssql` updated to only support Python 3.9+. Pin older Python versions to a compatible version of `pymssql`.
* v2.3.2 lists support for Python 3.7 and 3.8, but doesn't have prebuilt wheels and fails to build. v2.3.1 is used instead.
> Fix pymssql Tests

- newrelic/config.py
- newrelic/hooks/mlmodel_autogen.py
- tests/mlmodel_autogen/conftest.py
- tests/mlmodel_autogen/test_mcp_tool_adapter.py
- tox.ini
This PR adds instrumentation for the `from_server_params` function in `autogen` `MCPToolAdapter`.
> Add instrumentation for autogen MCP tool adapter.

- .github/scripts/install_azure_functions_worker.sh
- tests/adapter_mcp/test_mcp.py
* Fix for path changes in `azure-functions-worker` that prevented installing via `tox` scripting.
* Also patches tiny failure in MCP testing, where result contents are now in a container that needs unpacked.
> Fix Changed Paths in Azure Functions Install

- .github/workflows/tests.yml
- newrelic/config.py
- newrelic/hooks/database_oracledb.py
- tests/datastore_oracledb/conftest.py
- tests/datastore_oracledb/test_async_connection.py
- tests/datastore_oracledb/test_connection.py
- tests/datastore_oracledb/test_database.py
- tests/datastore_oracledb/test_instance_info.py
- tests/testing_support/db_settings.py
- tox.ini
* Add instrumentation for [oracledb](https://pypi.org/project/oracledb/).
* Instruments both sync and async connections through DBAPI2 when using `connect()` or `connect_async()`.
* Attempts to parse instance info from multiple sources, falling back to `"unknown"`. 
Closes #1420
> oracledb Package Instrumentation

- newrelic/common/utilization.py
- newrelic/core/application.py
- tests/agent_unittests/aws.json
- tests/agent_unittests/test_aws_utilization_caching.py
- tests/cross_agent/test_utilization_configs.py
This PR adds the AWS metadata to the utilization class.  This is for the specific case of when the agent is left continuously running and it is utilizing Kubernetes and AWS EC2 (but not EKS).
The utilization data is pulled the first time, but after this, the authentication token is unable to be refreshed.  The utilization data will remain the same as long as the same agent instance, so if the EC2 instance fails, the agent will restart (and not just reconnect) and the utilization data will be fetched for the new EC2 instance.
> Add caching for AWS metadata

- .github/workflows/addlicense.yml
- .github/workflows/build-ci-image.yml
- .github/workflows/mega-linter.yml
- .github/workflows/trivy.yml
* Add default permissions to all workflows to satisfy security scanning.
* Remove statuses permissions from Megalinter
* Also removes status reporter, a deprecated and buggy feature.
> Add Workflow Permissions

- newrelic/admin/run_program.py
- newrelic/admin/run_python.py
- setup.py
* Fix instances of calling `pathlib.Path.parent` on a command line path, that may have no parent directory listed.
* In these cases, this should search the `PATH` to find an executable of this name. Instead, the current change is interpreting no parent as `./`, producing incorrect results.
* Fix this by reverting to `os.path.dirname` for this specific use case, and ignore `PTH` linter.
* Tested locally with `newrelic-admin run-program flask run` and `newrelic-admin run-python main.py`.
* Can't find a decent way to test the `sys.argv[0]` being an executable with no path, but there's probably not a lot of risk. The comments indicate this is generally a Heroku only thing as well.
> Fix Issues Related to Path.parent with no Parent Directory

- tests/agent_unittests/conftest.py
- tests/agent_unittests/test_http_client.py
Previously the compression testing for the HttpClient included some odd choices in the testing infrastructure. The `echo_full_request()` function which served as the mock collector was intended to return an encoded form of the request as the response in a format consisting of a `\n` separated list of the request line, each header, and the request body.
This format caused issues in using zlib compression on windows when the compressed payload had a `0A` hex byte in the compressed payload. This coincidentally is `\n` when read as UTF-8, which broke the encoding strategy.
To fix this, the format is now a JSON list of `[request_line, headers, body]`. The headers are now a list of 2-item lists, and the body is encoded as a string of hex characters. There's also now a `decode_payload()` …
> Fix Compression Testing on Windows

- newrelic/config.py
- newrelic/hooks/adapter_mcp.py
- tests/adapter_mcp/conftest.py
- tests/adapter_mcp/test_mcp.py
This PR adds tool manager spans to MCP instrumentation to support streaming.
> MCP Streamable HTTP Spans (DO NOT MERGE YET)

- newrelic/core/_thread_utilization.c
- setup.py
* Refactors our `_thread_utilization.c` extension to support Windows by abstracting timestamp retrieval to a universal function.
* Re-enables this C extension on Windows in `setup.py`
> Windows Thread Utilization

- .github/workflows/deploy.yml
* Specify file extensions of artifacts to attest on deploy to remove attestations of attestations.
* See [example](https://github.com/newrelic/newrelic-python-agent/attestations/9684065) where there are attestations for `.publish.attestation` files. These are attestations for PyPI and should not be included.
> More Specific Attestation List

- newrelic/hooks/datastore_elasticsearch.py
- tests/datastore_elasticsearch/test_async_elasticsearch.py
- tests/datastore_elasticsearch/test_async_instrumented_methods.py
- tests/datastore_elasticsearch/test_instrumented_methods.py
This PR removes wrapping for the method `options` on the async ES client. This method does not need to be wrapped in a `DatastoreTrace` since it is focused on modifying the client with custom config rather than conducting any datastore operations/ requests. The previous instrumentation caused a crash because the wrapper was expecting all client methods to be async but `options` is actually a sync method.
> Remove instrumentation for options method on async ElasticSearch client.

- tox.ini
* Fix tests for Falcon by removing unsupported 3.8 version test on master branch.
> Fix Falcon Tests for master Branch

- .github/workflows/build-ci-image.yml
Recently we added caching to CI image builds. Unfortunately, this makes every single build a no-op as there's nothing in the image definition to bust the cache. This prevents us from getting the intended behavior of regularly updating dependencies and Python versions.
> Drop CI Image Build Caching

- newrelic/config.py
This PR adds a section to `newrelic/config.py` that issues a deprecation warning when a currently unsupported framework is still being used by the customer.
> Add deprecation warning for modules

- tests/testing_support/fixtures.py
* Fix issues with race condition in test startup by adding additional delay to the `collector_available_fixture`.
> Add Additional Delay to Test Startup Fixture

- tox.ini
There have been issues building the cryptography package in pypy310, so this test suite has been removed for now in `pymysql` and `aiomysql`
> Temporarily remove pypy310 test from pymysql and aiomysql

- tox.ini
This PR changes the versions tested in Falcon and Sanic:
- Falcon's master branch has [dropped Python 3.8 support](https://github.com/falconry/falcon/pull/2528)
- Remove versions of Sanic from test suite that are older than 3 years.
> Falcon sanic testing fix

- .gitignore
- newrelic/config.py
- newrelic/hooks/external_pyzeebe.py
- tests/external_pyzeebe/_mocks.py
- tests/external_pyzeebe/test_client.py
* Format main with ruff to fix linting issues.
* Add `version.py` and `_version.py` files to gitignore.
> Format main with ruff

- tox.ini
* Remove `pypy` testing for `pyzeebe` which depends on `grpcio`, which does not build `pypy` wheels. 
* This causes a 18 minute compile time before running the tests.
> Remove PyPy From PyZeebe Tests

- newrelic/hooks/framework_django.py
* Remove calls to `application_settings()` in Django instrumentation to prevent issues with early activations in `pre-fork` applications.
Fixes #1521
> Prevent Early Activations in Django Instrumentation

- newrelic/core/context.py
* In the `ContextOf` class, there was an unsafe access of the `trace_cache` via `pop(key)` without a default value. This caused crashes when the `weakref` in the dictionary was already garbage collected.
> Guard against crashes from trace_cache.pop()

- .github/workflows/tests.yml
* Tweak the "on runner" setup for the CI to also use `uv` as a package resolver and virtualenv manager for both speed and reliability.
> Use uv on Windows Runners

- newrelic/hooks/mlmodel_gemini.py
- tests/mlmodel_gemini/test_embeddings.py
- tests/mlmodel_gemini/test_embeddings_error.py
- tests/mlmodel_gemini/test_text_generation.py
- tests/mlmodel_gemini/test_text_generation_error.py
- tests/testing_support/ml_testing_utils.py
This PR updates Gemini instrumentation and tests to pull token counts directly from the response object. If a customer has an LLM token counting callback function registered, this will still take priority over the response token count values. 
It also removes token count calculations from error cases as the agent will consistently stop reporting token counts when a error was met during the creation of a text generation.
> Add response token count logic to Gemini instrumentation.
