ROADMAP.md
Add standard roadmap file required by New Relic Product.
=> Add Roadmap.

.github/pull_request_template.md
Add standard PR template required by New Relic Product.
=> Add Pull Request template.

.github/workflows/tests.yml, tests/framework_starlette/_target_application.py, tests/framework_starlette/conftest.py, tests/framework_starlette/test_application.py, tests/framework_starlette/tox.ini
This PR adds testing for Starlette.
=> Add Starlette framework tests

.github/workflows/tests.yml, newrelic/hooks/database_asyncpg.py, tests/datastore_asyncpg/conftest.py, tests/datastore_asyncpg/test_multiple_dbs.py, tests/datastore_asyncpg/test_query.py, tests/datastore_asyncpg/tox.ini, tests/framework_starlette/tox.ini, tests/testing_support/db_settings.py
This is a github actions compatible port of our internal asyncpg test suite.
@TimPansino 
PYTHON-3765
=> Add asyncpg test suite.

.github/workflows/tests.yml, tests/framework_sanic/_target_application.py, tests/framework_sanic/conftest.py, tests/framework_sanic/test_application.py, tests/framework_sanic/test_cross_application.py, tests/framework_sanic/tox.ini
This PR adds Sanic framework tests.
=> Add Sanic framework test suite

.github/workflows/tests.yml, tests/adapter_uvicorn/conftest.py, tests/adapter_uvicorn/test_uvicorn.py, tests/adapter_uvicorn/tox.ini
This PR adds tests for uvicorn. 
=> Add uvicorn test suite.

.github/workflows/tests.yml, tests/framework_bottle/_target_application.py, tests/framework_bottle/conftest.py, tests/framework_bottle/test_application.py, tests/framework_bottle/tox.ini
This PR adds Bottle framework tests.
=> Add Bottle framework tests

.github/workflows/tests.yml, tests/adapter_cheroot/conftest.py, tests/adapter_cheroot/test_wsgi.py, tests/adapter_cheroot/tox.ini
Add adapter_cheroot tests.
PYTHON-3772
=> Add adapter_cheroot tests.

.github/workflows/tests.yml, newrelic/hooks/datastore_redis.py, tests/datastore_redis/conftest.py, tests/datastore_redis/test_custom_conn_pool.py, tests/datastore_redis/test_execute_command.py, tests/datastore_redis/test_get_and_set.py, tests/datastore_redis/test_instance_info.py, tests/datastore_redis/test_multiple_dbs.py, tests/datastore_redis/test_rb.py, tests/datastore_redis/test_span_event.py, tests/datastore_redis/test_trace_node.py, tests/datastore_redis/tox.ini, tests/testing_support/db_settings.py
Adds redis testing workflow.
PYTHON-3808
=> Redis tests.

.github/workflows/tests.yml, newrelic/config.py, tests/component_flask_rest/_test_application.py, tests/component_flask_rest/conftest.py, tests/component_flask_rest/test_application.py, tests/component_flask_rest/tox.ini
Adds `component_flask_rest` tests, and adds support for `flask_restx`.
PYTHON-3781, PYTHON-3782
=> Add flask restful/plus/x tests.

.github/workflows/tests.yml, tests/framework_pyramid/_test_append_slash_app.py, tests/framework_pyramid/_test_application.py, tests/framework_pyramid/conftest.py, tests/framework_pyramid/test_append_slash_app.py, tests/framework_pyramid/test_application.py, tests/framework_pyramid/test_cornice.py, tests/framework_pyramid/tox.ini
Adds pyramid and cornice testing.
PYTHON-3829/PYTHON-3779
=> Add pyramid and cornice tests.

.github/workflows/tests.yml, tests/framework_cherrypy/conftest.py, tests/framework_cherrypy/test_application.py, tests/framework_cherrypy/test_dispatch.py, tests/framework_cherrypy/test_resource.py, tests/framework_cherrypy/test_routes.py, tests/framework_cherrypy/tox.ini
This PR adds tests for the CherryPy framework.
=> Add cherrypy framework tests

.github/workflows/tests.yml, tests/adapter_gevent/_application.py, tests/adapter_gevent/conftest.py, tests/adapter_gevent/test_patch_thread.py, tests/adapter_gevent/test_pywsgi.py, tests/adapter_gevent/tox.ini
=> Add gevent tests.

.github/workflows/tests.yml, tests/datastore_mysql/conftest.py, tests/datastore_mysql/test_database.py, tests/datastore_mysql/tox.ini
=> Add MySQL test suite

.github/workflows/tests.yml, tests/datastore_pymongo/conftest.py, tests/datastore_pymongo/test_pymongo.py, tests/datastore_pymongo/tox.ini, tests/testing_support/db_settings.py
* Add job for mongodb tests.
* Import pymongo tests from internal repo.
=> pymongo Tests

.github/workflows/tests.yml, tests/datastore_pylibmc/conftest.py, tests/datastore_pylibmc/test_memcache.py, tests/datastore_pylibmc/tox.ini
* Import pylibmc tests from internal repo.
* Remove version and extension based testing (no additional coverage gained)
=> pylibmc Tests

.github/workflows/tests.yml, tests/datastore_psycopg2/conftest.py, tests/datastore_psycopg2/test_as_string.py, tests/datastore_psycopg2/test_async.py, tests/datastore_psycopg2/test_cursor.py, tests/datastore_psycopg2/test_database_instance_info.py, tests/datastore_psycopg2/test_explain_plans.py, tests/datastore_psycopg2/test_forward_compat.py, tests/datastore_psycopg2/test_multiple_dbs.py, tests/datastore_psycopg2/test_obfuscation.py, tests/datastore_psycopg2/test_register.py, tests/datastore_psycopg2/test_rollback.py, tests/datastore_psycopg2/test_slow_sql.py, tests/datastore_psycopg2/test_span_event.py, tests/datastore_psycopg2/test_trace_node.py, tests/datastore_psycopg2/tox.ini, tests/datastore_psycopg2/utils.py, tests/testing_support/db_settings.py, tests/testing_support/validators/validate_database_node.py, tests/testing_support/validators/validate_sql_obfuscation.py, tests/testing_support/validators/validate_transaction_slow_sql_count.py
=> Add psycopg2 tests.

.github/workflows/tests.yml, tests/datastore_pymysql/conftest.py, tests/datastore_pymysql/test_database.py, tests/datastore_pymysql/tox.ini
* Import pymysql tests
* Expand coverage reporting of pymysql
* Upgrade pymysql tested version to 0.11
* Remove now unused rollback test
=> pymysql Tests

.github/workflows/tests.yml, tests/messagebroker_pika/compat.py, tests/messagebroker_pika/conftest.py, tests/messagebroker_pika/minversion.py, tests/messagebroker_pika/test_cat.py, tests/messagebroker_pika/test_distributed_tracing.py, tests/messagebroker_pika/test_memory_leak.py, tests/messagebroker_pika/test_pika_async_connection_consume.py, tests/messagebroker_pika/test_pika_blocking_connection_consume.py, tests/messagebroker_pika/test_pika_blocking_connection_consume_generator.py, tests/messagebroker_pika/test_pika_produce.py, tests/messagebroker_pika/test_pika_supportability.py, tests/messagebroker_pika/tox.ini, tests/testing_support/db_settings.py, tests/testing_support/external_fixtures.py, tests/testing_support/validators/validate_messagebroker_headers.py
=> Add messagebroker_pika tests

.github/workflows/tests.yml, tests/external_boto3/conftest.py, tests/external_boto3/test_boto3_iam.py, tests/external_boto3/test_boto3_s3.py, tests/external_boto3/test_boto3_sns.py, tests/external_boto3/tox.ini
* Import boto3 tests from internal repo.
* Clean tox file and reduce version matrix.
=> boto3 Tests

.github/workflows/tests.yml, tests/datastore_sqlite/conftest.py, tests/datastore_sqlite/test_database.py, tests/datastore_sqlite/test_obfuscation.py, tests/datastore_sqlite/tox.ini
Sidekick: @TimPansino 
This PR adds the SQLite test suite. 
exercise your …
=> Add SQLite test suite

.github/workflows/tests.yml, tests/external_botocore/conftest.py, tests/external_botocore/test_botocore_dynamodb.py, tests/external_botocore/test_botocore_ec2.py, tests/external_botocore/test_botocore_s3.py, tests/external_botocore/test_botocore_sqs.py, tests/external_botocore/tox.ini
* Import botocore tests from internal repo.
* Reduce test matrix based on coverage.
=> botocore Tests

.github/workflows/tests.yml, tests/datastore_pysolr/conftest.py, tests/datastore_pysolr/test_solr.py, tests/datastore_pysolr/tox.ini, tests/testing_support/db_settings.py
* Import pysolr tests from internal repo.
* Upgrade tests with namespacing for concurrency issues.
* Add solr workflow to GHA
=> pysolr Tests

.github/workflows/tests.yml, tests/datastore_solrpy/conftest.py, tests/datastore_solrpy/test_solr.py, tests/datastore_solrpy/tox.ini
* Import solrpy tests from internal repo.
=> solrpy Tests

.github/workflows/tests.yml, tests/external_httplib2/conftest.py, tests/external_httplib2/test_httplib2.py, tests/external_httplib2/tox.ini, tests/testing_support/external_fixtures.py
This PR add tests for httplib2.
=> Add httplib2 tests

.github/workflows/tests.yml, tests/template_mako/conftest.py, tests/template_mako/test_mako.py, tests/template_mako/tox.ini
=> Add mako tests

.github/workflows/tests.yml, tests/external_requests/conftest.py, tests/external_requests/test_requests.py, tests/external_requests/test_span_event.py, tests/external_requests/tox.ini, tests/framework_flask/test_compress.py
* Import requests tests from internal repo
* Massively prune version matrix based on coverage
* Clean up a few comments in other test suites
=> requests Tests

.github/workflows/tests.yml, tests/external_feedparser/conftest.py, tests/external_feedparser/packages.xml, tests/external_feedparser/test_feedparser.py, tests/external_feedparser/tox.ini
* Import feedparser tests from internal repo.
* Add testing for new major version of feedparser.
=> feedparser Tests

.github/workflows/tests.yml, tests/external_http/conftest.py, tests/external_http/test_http.py, tests/external_http/tox.ini, tests/testing_support/external_fixtures.py
This PR adds the test suite for external_http, and adds related fixtures to external fixtures. 
For most contributions it is strongly recommended to add …
=> Add http test suite.

.github/workflows/tests.yml, tests/datastore_umemcache/conftest.py, tests/datastore_umemcache/test_memcache.py, tests/datastore_umemcache/tox.ini
This PR adds the umemcache test suite, and adds support for concurrency for testing within Github Actions. 
For most contributions it is strongly recommended to …
=> Add umemcache test suite

.github/workflows/tests.yml, tests/component_tastypie/api.py, tests/component_tastypie/conftest.py, tests/component_tastypie/settings.py, tests/component_tastypie/test_application.py, tests/component_tastypie/tox.ini, tests/component_tastypie/urls.py, tests/component_tastypie/views.py, tests/component_tastypie/wsgi.py
* Import tastypie tests from internal repo
* Clean up settings.py and tox files
=> tastypie Tests

.github/workflows/tests.yml, tests/external_httplib/conftest.py, tests/external_httplib/test_httplib.py, tests/external_httplib/test_urllib.py, tests/external_httplib/test_urllib2.py, tests/external_httplib/tox.ini
This PR adds tests for httplib.
=> Add httplib tests

.github/workflows/tests.yml, tests/coroutines_asyncio/conftest.py, tests/coroutines_asyncio/test_context_propagation.py, tests/coroutines_asyncio/tox.ini
* Import asyncio tests from internal repo.
=> asyncio Tests

.github/workflows/tests.yml, tests/component_djangorestframework/conftest.py, tests/component_djangorestframework/settings.py, tests/component_djangorestframework/test_application.py, tests/component_djangorestframework/tox.ini, tests/component_djangorestframework/urls.py, tests/component_djangorestframework/views.py, tests/component_djangorestframework/wsgi.py
* Import tests from internal repo.
* Reduce matrix of versions tested.
=> djangorestframework Tests

.github/workflows/tests.yml, tests/external_urllib3/conftest.py, tests/external_urllib3/test_urllib3.py, tests/external_urllib3/tox.ini, tests/testing_support/external_fixtures.py
Sidekick: @TimPansino 
This PR adds the urllib3 test suite, and updates the test matrix. 
=> Add urllib3 test suite

.github/workflows/tests.yml, tests/framework_grpc/_test_common.py, tests/framework_grpc/conftest.py, tests/framework_grpc/sample_application/.gitignore, tests/framework_grpc/sample_application/README.md, tests/framework_grpc/sample_application/__init__.py, tests/framework_grpc/sample_application/sample_application.proto, tests/framework_grpc/test_clients.py, tests/framework_grpc/test_distributed_tracing.py, tests/framework_grpc/test_get_url.py, tests/framework_grpc/test_server.py, tests/framework_grpc/tox.ini, tests/testing_support/mock_external_grpc_server.py
* Import grpc tests from internal repo.
* Reduce testing matrix for grpc.
=> grpc Tests

.github/workflows/tests.yml, tests/application_gearman/conftest.py, tests/application_gearman/test_gearman.py, tests/application_gearman/tox.ini
This PR adds tests for gearman.
=> Add gearman tests

.github/workflows/tests.yml
* Unpin setup-python github action after bugfix.
=> Unpin setup-python after bugfix

tests/framework_grpc/conftest.py, tests/framework_grpc/test_server.py
* Optimize grpc test suite.
* Extract stub and channel to sessionized fixtures.
* Restrict garbage collection fixture to only run with python 2.7.
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#testing-gui …
=> Optimize Grpc Tests

.github/workflows/get-envs.py, .github/workflows/tests.yml
* Run mixed tests suites in slices on multiple runners to distribute load.
For most contributions it is strongly recommended to add …
=> Test Suite Slicing

tests/agent_features/test_exception_messages.py, tests/agent_features/test_stack_trace.py, tests/cross_agent/test_cat_map.py, tests/testing_support/fixtures.py
* Synchronize the last changes made to the internal repo. 
* As of this PR, the internal repo will be archived.
For most contributions …
=> Synchronize With Internal Repo

newrelic/config.py, newrelic/hooks/adapter_asgiref.py, newrelic/hooks/framework_django.py, newrelic/hooks/framework_django_py3.py, tests/framework_django/conftest.py, tests/framework_django/test_asgi_application.py
This PR adds automatic transaction support for Django's ASGI application.
#31
=> Add django ASGI instrumentation. #31

newrelic/config.py, newrelic/hooks/external_httpx.py, tests/external_httpx/conftest.py, tests/external_httpx/test_client.py, tox.ini
Adds initial scaffold for httpx instrumentation points and tests.
=> Add scaffold for httpx instrumentation. #100

newrelic/hooks/external_httpx.py, tests/external_httpx/conftest.py, tests/external_httpx/test_client.py
* Add distributed tracing headers to outbound requests using httpx.
Closes: #101 
=> Add httpx DT headers. #101

newrelic/hooks/external_httpx.py, tests/external_httpx/test_client.py
* Fix the issue where an exception raised in an event hook caused response status_code and CAT headers not to be processed.
Closes #116
For most contributions it is strongly recommended to add …
=> Fix httpx event_hook exception bug #116

newrelic/hooks/external_httpx.py, tests/external_httpx/test_client.py
This Pull Request changes the httpx event hook logic to use the external trace to process responses rather than the current trace.
For most contributions it is …
=> Fix event hook response processing regression

newrelic/core/agent.py, newrelic/samplers/gc_data.py
This PR adds metrics for garbage collector object count. 
#126 
=> Add garbage collector object count metrics. #126

newrelic/samplers/gc_data.py
* Add gc.get_stats information as metrics.
Closes #127 
=> Add gc.get_stats metrics. #127

newrelic/samplers/gc_data.py, tests/agent_unittests/test_gc_metrics.py
* Add scaffolding for unit testing the new GC data source.
* Add unit tests for existing metrics.
=> GC Data Source Unit Tests

newrelic/samplers/gc_data.py, tests/agent_unittests/test_gc_metrics.py
=> Add gc timing metrics. #125 

newrelic/samplers/gc_data.py, tests/agent_unittests/test_gc_metrics.py
* Add PID to all GC metrics to allow faceting. 
=> Add PID to GC metrics.

newrelic/samplers/gc_data.py, tests/agent_unittests/test_gc_metrics.py
This PR adds metrics to record the top five object types with highest count that are tracked by the garbage collector.
Closes #137
exercise …
=> Add garbage collector object count by type metrics. #137

newrelic/config.py, newrelic/core/config.py, newrelic/samplers/gc_data.py, tests/agent_unittests/test_gc_metrics.py
* Add enable setting to new to gc_profiler section. Defaults to False.
* Add top_object_count_limit to above section. Defaults to 5.
Closes #134
=> Add gc config options.

newrelic/samplers/memory_usage.py, tests/agent_unittests/test_memory_metrics.py
This PR adds a metric to the memory usage data sampler for percent memory utilization and tests to verify expected metrics.
For most contributions it is strongly …
=> Add Memory Utilization Metrics and Tests.

newrelic/samplers/cpu_usage.py, tests/agent_unittests/test_cpu_sampler.py
* Add additional CPU utilization metrics to data sampler.
https://github.com/newrelic/python-work-tracking/issues/4
=> Add New CPU Metrics to Sampler

newrelic/api/cat_header_mixin.py, newrelic/api/transaction.py, newrelic/common/encoding_utils.py, tests/agent_features/test_cat.py, tests/cross_agent/test_cat_map.py
* Fix bug with FIPS compliant systems crashing when attempting to generate CAT headers.
* Add regression and no harm testing.
* Fix minor spelling error.
* Sort imports in `encoding_utils`.
Closes #32
For most …
=> Fix issue with FIPS compliance and CAT.

tox.ini
* Fix failing boto tests by pinning moto major version.
N/A
=> Pin moto version for tox environments.

newrelic/config.py, newrelic/core/config.py, newrelic/samplers/gc_data.py, tests/agent_unittests/test_sampler_metrics.py
* Renaming setting to not use the word "profiler" to be clearer in intent.
N/A
=> Rename GC settings to gc_runtime_metrics.

.github/workflows/deploy.yml
* Changes py27 wheel builds to use forked manylinux wheel build action.
Closes #157
=> Pin manylinux for py27.

tox.ini
* Pin version of `mysql-connector-python` on python 27 to last applicable version.
* Temporarily move Django version to latest release while we wait for master to be fixed.
N/A
For most contributions it is strongly …
=> Pin dependencies to fix tests.

newrelic/config.py, newrelic/core/config.py
This PR adds new settings for expected error status codes and classes.
=> Add expected errors settings

tests/agent_features/test_ignore_expected_errors.py
* Add test_ignore_expected_errors with matrix of functionality.
Closes #187
=> Add testing for ignore/expected errors.

newrelic/api/log.py, newrelic/api/time_trace.py, newrelic/api/transaction.py, newrelic/core/config.py, newrelic/core/error_collector.py, newrelic/core/error_node.py, newrelic/core/stats_engine.py, newrelic/core/transaction_node.py, tests/agent_features/test_ignore_expected_errors.py, tests/agent_features/test_logs_in_context.py, tests/agent_unittests/test_harvest_loop.py
* Add logic for matching expected error classes
* Rewrite interface to be able to match either fullname or module and type.
* Add testing for errors outside of transactions.
* Rip out old ignore_errors/ignore_classes logic and replace with new interfaces.
* Correct log format_exc_info to use newer style of `module:class` for exception types.
Closes #193
Github Actions when a pull request is made. More details on running …
=> Expected error rule matching

newrelic/api/error_trace.py, newrelic/config.py, newrelic/hooks/framework_cherrypy.py
This PR adds status code and expected error class parameters to the error trace wrapper.
Closes #212
=> Update error trace with status code and expected errors

tests/agent_features/test_ignore_expected_errors.py, tests/testing_support/fixtures.py
* Add testing for TracedErrors to ensure expected attributes are correctly applied.
Closes #191
=> Add testing for error trace attributes.

newrelic/core/stats_engine.py, newrelic/core/transaction_node.py
=> Add metric logic for expected errors.

newrelic/api/time_trace.py, newrelic/api/transaction.py, newrelic/core/trace_cache.py, tests/agent_features/test_background_task.py
* Remove exceptions that could be raised in complete_root.
N/A
=> Remove possible exceptions in complete_root.

newrelic/core/config.py
* Add serverside-config mapping for ignore_errors to ignore_classes.
N/A
=> Add mapping for ignore_errors to ignore_classes in SSC.

newrelic/config.py, newrelic/core/config.py
* Fix issue with ignore_errors setting not being processed. 
N/A
=> Correct processing of deprecated ignore_errors setting

tests/framework_flask/_test_blueprints.py, tests/framework_flask/test_blueprints.py, tests/framework_flask/test_not_found.py, tests/framework_flask/test_user_exceptions.py, tox.ini
This PR adds testing for nested blueprints which are a new feature in Flask v2.
Closes #235.
=> Add testing for Flask nested blueprints. 

.github/workflows/tests.yml
* Add `feature/` and `feature-` branch prefixes to tested pull request branches.
=> Add feature branches to GHA workflows

tests/framework_flask/_test_application.py, tests/framework_flask/_test_application_async.py, tests/framework_flask/_test_views_async.py, tests/framework_flask/test_application.py, tests/framework_flask/test_views.py, tox.ini
* Reintroduce version based logic for flask testing
=> Restore required flask version testing

tests/framework_flask/_test_application_async.py, tests/framework_flask/_test_blueprints.py, tests/framework_flask/_test_views_async.py, tests/framework_flask/conftest.py, tests/framework_flask/test_application.py, tests/framework_flask/test_blueprints.py, tests/framework_flask/test_views.py
* Remove unsupported async testing on PyPy3
N/A
=> Fix pypy async flask

newrelic/hooks/framework_sanic.py, tests/framework_sanic/_target_application.py, tests/framework_sanic/conftest.py, tests/framework_sanic/test_application.py, tests/framework_sanic/test_cross_application.py, tests/testing_support/fixtures.py, tox.ini
* Update sanic to fix issues on all supported versions.
Closes #162
=> Sanic Updates

newrelic/console.py
* Fix deprecation warning of inspect.formatargspec
N/A
=> Fix deprecation warning of formatargspec

newrelic/hooks/framework_sanic.py, tests/framework_sanic/_target_application.py, tests/framework_sanic/test_application.py
This PR adds a new instrumentation point for Sanic blueprint middleware and associated testing.
https://github.com/newrelic/python-work-tracking/issues/43
=> Add Sanic blueprint middleware instrumentation 

tests/framework_starlette/test_application.py, tox.ini
* Fix failing tests after Starlette v0.15.0.
N/A
=> Fix starlette tests for new release

newrelic/config.py, tests/agent_unittests/_test_import_hook.py, tests/agent_unittests/test_import_hook.py
* Add support for file globbing syntax (eg. wildcarding) to import hook config.
Closes #270
=> Wildcarding in Import Hook Config

newrelic/hooks/framework_graphql.py, tests/framework_graphql/_target_application.py, tests/framework_graphql/test_application.py
* Add a featureful test application for graphql, including nested object types.
N/A
=> GraphQL Test Application

newrelic/api/graphql_trace.py, newrelic/core/attribute.py, newrelic/core/graphql_node.py, newrelic/hooks/framework_graphql.py, tests/framework_graphql/test_application.py, tox.ini
This PR adds field resolver metrics and span attributes.
Note: Some test metrics named after field resolvers are commented out since resolver name in those cases will be replaced with deepest path in a future PR.
#263
=>  Add field resolver metrics and span attributes.

newrelic/api/graphql_trace.py, newrelic/core/attribute.py, newrelic/core/graphql_node.py, newrelic/hooks/framework_graphql.py, tests/framework_graphql/test_application.py
* Add metrics and attributes for graphql operations
* Separate graphql traces into resolver and operation traces
* Clean up code base and remove unnecessary code
Closes #259
Closes #261
For most contributions it is …
=> GraphQL Operation Metrics and Attrs

newrelic/api/graphql_trace.py, tests/framework_graphql/_target_application.py, tests/framework_graphql/test_application.py
This PR adds testing to verify metrics and span attributes for GraphQL mutations.
=> Add testing for GraphQL Mutation Types

newrelic/api/graphql_trace.py, newrelic/config.py, newrelic/core/graphql_node.py, newrelic/core/graphql_utils.py, newrelic/hooks/framework_graphql.py, tests/framework_graphql/_target_application.py, tests/framework_graphql/test_application.py
* Add obfuscated GraphQL queries as span attributes.
Closes #278
=> GraphQL Obfuscated Queries

newrelic/hooks/framework_graphql.py, tests/framework_graphql/test_application.py
This PR adds a GraphQL framework metric and removes a duplicated function definition.  
#260
=> Add GraphQL Framework Metric 

newrelic/api/graphql_trace.py, newrelic/config.py, newrelic/core/attribute.py, newrelic/core/graphql_node.py, newrelic/hooks/framework_graphql.py, tests/framework_graphql/_target_application.py, tests/framework_graphql/conftest.py, tests/framework_graphql/test_application.py, tests/framework_graphql/test_application_async.py, tox.ini
* Updates deepest path logic to deepest unique path.
* Removes deepest path attribute.
* Handle inline fragments
N/A
=> GraphQL Deepest Path Update

.github/workflows/tests.yml, newrelic/core/attribute.py, newrelic/hooks/framework_graphql.py, tests/framework_graphql/test_application.py, tests/framework_graphql/test_application_async.py
=> Add field resolver returnType span attribute

newrelic/hooks/framework_graphql.py, tests/framework_fastapi/_target_application.py, tests/framework_fastapi/test_application.py, tests/framework_graphene/_target_application.py, tests/framework_graphene/conftest.py, tests/framework_graphene/test_application.py, tests/framework_graphql/_target_application.py, tests/framework_graphql/test_application.py, tests/framework_graphql/test_application_async.py, tox.ini
* Add explicit testing for graphene.
* Correct small issues in graphql tests.
Closes #301
=> Graphene Testing

newrelic/api/html_insertion.py
* Tweak contribution to address original issue, and fixing incorrect types
N/A
=> Fix byte regular expressions

newrelic/hooks/framework_graphql.py
This PR updates version parsing to check the first two values in the graphql-core version. Previous logic included integer casting which causes ValueErrors with pre-release versions.
=> Update version parsing to prevent errors with graphql-core pre-release versions.

README.rst
Updates the readme header to use one with white background.
Closes #245
=> chore(docs): update newrelic header

newrelic/newrelic.ini
This PR updates the generated newrelic.ini to output logging to stderr by default. This update will allow users to receive immediate feedback when running the agent and customize logging afterward as needed.
=> Update Default Agent Logging

newrelic/common/log_file.py
* Disable propagation of `'newrelic'` logs to root logger.
Closes #328 
N/A
=> Disable Logger Propagation

tests/framework_graphql/_target_application.py
* Fix failing graphqlmaster test.
N/A
=> Fix failing graphql test

.github/workflows/mega-linter.yml, .github/workflows/tests.yml
* Remove GHA branch filters for PR triggers. Run on a PR into anything.
N/A
=> Fix GHA Config

tox.ini
* Tweak contribution of Django tests
N/A
N/A
=> Tweak Django Tox Config

newrelic/api/graphql_trace.py, newrelic/config.py, newrelic/hooks/framework_ariadne.py, newrelic/hooks/framework_graphql.py
This PR adds instrumentation for Ariadne's graphql execution function. 
Closes #345 
Closes #346
=> Add base ariadne execution instrumentation.

tests/framework_ariadne/_target_application.py, tests/framework_ariadne/conftest.py, tests/framework_ariadne/schema.graphql, tests/framework_ariadne/test_application.py, tests/framework_ariadne/test_application_async.py, tests/framework_graphene/_target_application.py, tests/framework_graphene/conftest.py, tests/framework_graphene/test_application.py, tox.ini
* Add testing for ariadne
Closes #349
=> Ariadne Tests

newrelic/config.py, newrelic/hooks/framework_ariadne.py, tests/framework_ariadne/_target_application.py, tests/framework_ariadne/test_application.py, tests/framework_ariadne/test_application_async.py, tests/framework_ariadne/test_asgi.py, tests/framework_ariadne/test_wsgi.py, tests/testing_support/validators/validate_span_events.py
* Add instrumentation for ariadne's WSGI and ASGI applications.
* Add testing for the above.
Closes #354
=> Ariadne WSGI/ASGI Support

newrelic/core/config.py
* Add environment variables for the 4 harvest limit config settings, following agent spec for naming.
N/A
=> Add harvest limit env vars

newrelic/core/config.py, tests/agent_features/test_configuration.py
=> Change span reservoir size

newrelic/config.py, newrelic/hooks/framework_strawberry.py, tests/framework_ariadne/test_application.py, tests/framework_strawberry/_target_application.py
* Add instrumentation for strawberry.
Closes #355
Closes #297
Closes #307
=> Strawberry Instrumentation

newrelic/config.py, newrelic/core/context.py, newrelic/hooks/adapter_asgiref.py, newrelic/hooks/framework_graphql.py, newrelic/hooks/framework_starlette.py, tests/framework_fastapi/_target_application.py, tests/framework_fastapi/test_application.py, tests/framework_starlette/_test_graphql.py, tests/framework_starlette/test_graphql.py, tox.ini
* Fix context propagation issue preventing synchronous GraphQL executors from tracing properly with Starlette.
Closes #348
=> Starlette GraphQL Context Propagation

.github/workflows/deploy-python.yml
* Remove build tests to speed back up release cycle.
=> Remove Build Tests

.github/workflows/deploy-python.yml, tests/framework_grpcaio/conftest.py, tests/framework_grpcaio/sample_application/.gitignore, tests/framework_grpcaio/sample_application/README.md, tests/framework_grpcaio/sample_application/__init__.py, tests/framework_grpcaio/sample_application/sample_application.proto, tests/framework_grpcaio/test_server.py, tests/testing_support/mock_external_grpc_aio_server.py, tox.ini
This PR adds testing setup for grpc aio instrumentation.
Closes #374.
=> Add grpc aio test infrastructure

tests/framework_sanic/_target_application.py, tox.ini
* Temporarily pin sanic tests to previous version until tests can be fixed.
* Fix a signature issue with sanic tests
N/A
exercise your …
=> Sanic Testing Fix

.github/workflows/mega-linter.yml, .github/workflows/tests.yml, .mega-linter.yml
* Add daily runs of test suite at 15 UTC (7 am PST)
N/A
=> Schedule daily test suite runs on main

newrelic/config.py, newrelic/hooks/framework_graphene.py, newrelic/hooks/framework_graphql.py, tests/framework_graphene/test_application.py, tests/framework_starlette/test_graphql.py, tox.ini
Co-authored-by: Timothy Pansino <TimPansino@users.noreply.github.com>
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTIN …
=> Fix graphene framework details

newrelic/common/system_info.py, newrelic/samplers/memory_usage.py
Fix crash in memory sampler on non-supported systems.
Closes #399
=> Fix memory sample exception

newrelic/newrelic.ini
This PR updates the default newrelic.ini with new links and further documentation.
=> Update default newrelic.ini.

newrelic/api/import_hook.py
=> Fix import hook warnings for Python 3.10+.

newrelic/hooks/framework_graphql.py, tests/testing_support/fixtures.py, tox.ini
* Fixes instrumentation for graphql-core on versions >=3.2
=> Add support for GraphQL v3.2

newrelic/core/context.py, newrelic/hooks/adapter_asgiref.py
Co-authored-by: Lalleh Rafeei <lrafeei@users.noreply.github.com>
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst …
=> Fix logging erroneous error messages in asgiref

newrelic/api/import_hook.py
* Unused raise was commented out in import hooks. Removed.
=> Remove Unused Raise

newrelic/api/import_hook.py, newrelic/config.py, newrelic/core/context.py, newrelic/hooks/adapter_asgiref.py, newrelic/hooks/datastore_redis.py, newrelic/hooks/framework_django.py, newrelic/hooks/framework_graphql.py, tests/component_tastypie/test_application.py, tests/datastore_redis/test_instance_info.py, tests/testing_support/fixtures.py, tox.ini
Merge develop into main for release v7.4.0.172
=> Release v7.4.0.172

newrelic/config.py, newrelic/hooks/datastore_aredis.py, tests/datastore_aredis/conftest.py, tests/datastore_aredis/test_execute_command.py, tox.ini
* Add aredis connection wrapper 
Closes #483 
N/A
=> Aredis connection wrapper 

newrelic/core/config.py, newrelic/samplers/gc_data.py
Co-authored-by: Elise Spain <elisespain@gmail.com>
Co-authored-by: Jessica Shortz <jshortz@newrelic.com>
Co-authored-by: Uma Annamalai <uannamalai@newrelic.com>
Fixed gc settings attribute error & added enable=False to GCRuntimeMetricsSettings to resolve test error.
=> fix gc settings attribute error.

newrelic/config.py, newrelic/hooks/datastore_aredis.py, tests/datastore_aredis/test_execute_command.py, tox.ini
Co-authored-by: Lalleh Rafeei <lrafeei@newrelic.com>
Co-authored-by: Jessica Shortz <jshortz@newrelic.com>
Co-authored-by: Charly DeFreitas <zdefreitas@newrelic.com>
This PR adds instrumentation for aredis methods and refactors the datastore_aredis.py file.
=> Add aredis method wrapper.

tests/datastore_aredis/test_custom_conn_pool.py, tests/datastore_aredis/test_execute_command.py, tests/datastore_aredis/test_get_and_set.py, tests/datastore_aredis/test_instance_info.py, tests/datastore_aredis/test_multiple_dbs.py, tests/datastore_aredis/test_span_event.py, tests/datastore_aredis/test_trace_node.py
This PR adds testing for the new aredis instrumentation.
=> Add aredis testing.

newrelic/common/utilization.py
=> Upgrade AWS metadata to IMDSv2

newrelic/config.py, newrelic/hooks/datastore_aredis.py, tests/datastore_aredis/conftest.py, tests/datastore_aredis/test_custom_conn_pool.py, tests/datastore_aredis/test_execute_command.py, tests/datastore_aredis/test_get_and_set.py, tests/datastore_aredis/test_instance_info.py, tests/datastore_aredis/test_multiple_dbs.py, tests/datastore_aredis/test_span_event.py, tests/datastore_aredis/test_trace_node.py, tox.ini
This PR adds new aredis instrumentation to the Python agent for the StrictRedis client.
=> Add aredis instrumentation for StrictRedis client.

newrelic/api/asgi_application.py, newrelic/api/time_trace.py, newrelic/core/stats_engine.py, newrelic/hooks/framework_aiohttp.py, newrelic/hooks/framework_starlette.py
* Pass references to settings where possible to should_ignore_error
* Make custom `_nr_ignored` logic more defined and incorporate into notice_error where it belongs, not `ASGIWebTransaction.__exit__`
N/A
For most …
=> More robust should_ignore_error calls

.gitignore, newrelic/api/log.py
I created a handler `NewRelicLogHandler` that can be used in python applications like Django as a log handler. The handler forwards logs to the API.
related to issue #439 
Please advise on this. I am not sure what and how to test given is suppose to make and API call
=> Created a log handler that forwards logs to new relic api

newrelic/api/log.py
* Clean log handler introduced in #495 to conform to New Relic's usual style
N/A
=> Log Handler Cleanup

newrelic/newrelic.ini
=> Add corresponding env vars to newrelic.ini.

newrelic/api/time_trace.py, newrelic/api/transaction.py, newrelic/config.py, newrelic/core/application.py, newrelic/core/config.py, newrelic/core/environment.py, newrelic/core/rules_engine.py, newrelic/core/stats_engine.py, newrelic/packages/urllib3/util/retry.py, tests/agent_features/test_configuration.py, tests/agent_features/test_notice_error.py, tests/agent_unittests/test_harvest_loop.py
Update language (removing whitelist / blacklist and replacing with allowlist / denylist)
=> Replace instances of whitelist/blacklist to allowlist/denylist

newrelic/api/time_trace.py
* Fixed small bug with code level metrics where settings may not be available.
* Downgraded code level metrics exception log to debug level to avoid spamming customers.
* Added exception info to code level metrics failure log message. …
=> Patch settings and logs for code level metrics

newrelic/config.py, newrelic/core/config.py, newrelic/hooks/framework_starlette.py
This PR adds settings to configure all application logging functionality. 
Closes #535
=> Logging config settings

newrelic/config.py, newrelic/core/agent_protocol.py, newrelic/core/config.py, tests/agent_features/test_configuration.py, tests/agent_features/test_high_security_mode.py
Co-authored-by: Lalleh Rafeei lrafeei@users.noreply.github.com
Co-authored-by: Tim Pansino timpansino@users.noreply.github.com
This PR updates logging configuration and includes testing.
=> Update settings for logging (HSM, harvest config)

newrelic/config.py, newrelic/hooks/framework_starlette.py, tests/framework_starlette/_test_bg_tasks.py, tests/framework_starlette/test_application.py, tests/framework_starlette/test_bg_tasks.py, tests/testing_support/fixtures.py, tox.ini
Co-authored-by: Timothy Pansino <TimPansino@users.noreply.github.com>
This PR fixes the agent's instrumentation of Starlette after the release of Starlette v0.20.1
=> Fix Starlette instrumentation after 0.20.1 release

newrelic/core/application.py, tests/agent_unittests/test_agent_connect.py, tests/testing_support/fixtures.py
Co-authored-by: Lalleh Rafeei lrafeei@users.noreply.github.com
Co-authored-by: Uma Annamalai umaannamalai@users.noreply.github.com
Co-authored-by: Tim Pansino timpansino@users.noreply.github.com
=> Add logging supportability metrics

newrelic/newrelic.ini
This PR adds settings related to application logging to the default `newrelic.ini`.
=> Add application logging settings to newrelic.ini.

tests/logger_loguru/test_local_decorating.py, tests/logger_loguru/test_log_forwarding.py, tests/logger_loguru/test_metrics.py
* Clean up testing for `logging` and `loguru`
* Add extra tests to `loguru` for `patch` and `catch` decorators
For most contributions it is strongly recommended …
=> Logging Testing Cleanup

tox.ini
* Disable flask master tests until flask is passing again.
=> Disable Flaskmaster tests

newrelic/config.py, newrelic/hooks/datastore_aioredis.py, newrelic/hooks/datastore_aredis.py
Co-authored-by: Nyenty Ayuk <ayuknyenty15@gmail.com>
Co-authored-by: ccedacero-nr <ccedacero-nr@users.noreply.github.com>
* Adds instrumentation for aioredis
N/A
=> Add aioredis Instrumentation

newrelic/api/transaction.py, tests/datastore_aioredis/conftest.py, tests/datastore_aioredis/test_get_and_set.py, tox.ini
This PR adds scaffolding for aioredis instrumentation tests.
=> Add aioredis test infrastructure.

tox.ini
=> Add PYPY 3.7 tox tests

newrelic/config.py, newrelic/core/environment.py, newrelic/hooks/adapter_daphne.py, tests/adapter_daphne/conftest.py, tests/adapter_daphne/test_daphne.py, tox.ini
* Add instrumentation for Daphne, a Django project ASGI server. 
* Supports both ASGI 2/3, testing included for all current minor versions v2.4+.
https://issues.newrelic.com/browse/NR-40072
=> Daphne ASGI Server Instrumentation

newrelic/api/database_trace.py
=> Fix sql_format error on database_trace

newrelic/api/message_transaction.py, newrelic/config.py, newrelic/hooks/messagebroker_kafkapython.py, tests/messagebroker_kafkapython/test_heartbeat.py, tests/messagebroker_kafkapython/test_kafka_consumer.py
Add kafka-python consumer instrumentation.
[Python Kafka Implementation](https://issues.newrelic.com/browse/NR-12666).
=> Add kafka python consumer

newrelic/api/transaction.py, newrelic/core/config.py, tests/agent_features/test_configuration.py
Reverts newrelic/newrelic-python-agent#591
Feature release is blocked by messaging from marketing, reverting unreleased feature to unblock releases. Will be published at a later date.
=> Revert "Custom Event Limit Increase"

.mega-linter.yml
=> Add Bandit TOML Support to Megalinter

.github/workflows/tests.yml, newrelic/config.py, newrelic/hooks/messagebroker_confluentkafka.py, tests/messagebroker_confluentkafka/conftest.py, tests/messagebroker_confluentkafka/test_consumer.py, tests/messagebroker_confluentkafka/test_producer.py, tests/messagebroker_confluentkafka/test_serialization.py, tests/messagebroker_kafkapython/conftest.py, tox.ini
Add support for confluent-kafka instrumentation.
=> Confluent Kafka Instrumentation

tox.ini
=> Pin incompatibility version dependencies in tests.

newrelic/packages/wrapt/__init__.py, newrelic/packages/wrapt/_wrappers.c, newrelic/packages/wrapt/arguments.py, newrelic/packages/wrapt/decorators.py, newrelic/packages/wrapt/importer.py, newrelic/packages/wrapt/wrappers.py
* Update vendored wrapt version to latest (v1.14.1).
Fixes #637
=> Update wrapt to v1.14.1

newrelic/api/asgi_application.py, newrelic/api/transaction.py, newrelic/api/wsgi_application.py, newrelic/hooks/adapter_daphne.py, newrelic/hooks/adapter_hypercorn.py, tests/adapter_daphne/test_daphne.py, tests/adapter_hypercorn/test_hypercorn.py
This PR adds a dispatcher metric for Daphne and Hypercorn to track usage.
=> Add usage metrics for Daphne and Hypercorn.

newrelic/agent.py
Uncomment NewRelicContextFormatter import from newrelic/agent.py
=> Uncomment NewRelicContextFormatter from agent.py

.github/workflows/tests.yml
=> Increase Kafka Test Parallelization

newrelic/hooks/mlmodel_sklearn.py, tests/mlmodel_sklearn/test_feature_events.py
Report the feature event w/o the raw value if `machine_learning.inference_event_value.enabled` is False.
=> Report feature event w/o value

newrelic/config.py, newrelic/core/config.py
This PR adds additional batching and compression settings for Infinite Tracing (for now, these are boolean values)
=> Infinite Tracing Batching and Compression settings

newrelic/core/agent_streaming.py, newrelic/core/config.py, newrelic/core/data_collector.py, tests/agent_streaming/conftest.py, tests/agent_streaming/test_streaming_rpc.py
This PR has GZIP compression implemented for Infinite Tracing
=> Infinite Tracing Compression

newrelic/common/package_version_utils.py, newrelic/config.py, newrelic/hooks/datastore_aioredis.py, tests/agent_unittests/test_package_version_utils.py, tests/datastore_aioredis/conftest.py, tests/datastore_aioredis/test_instance_info.py, tests/datastore_aioredis/test_multiple_dbs.py, tests/datastore_aioredis/test_uninstrumented_methods.py, tox.ini
Merge feature development branch into main.
=> Redis.Asyncio Support

CONTRIBUTING.rst
This PR updates a Slack link in the CONTRIBUTING.rst.
=> Update contributors workspace link in CONTRIBUTING.rst.

newrelic/config.py
This PR fixes some linter errors in newrelic/config.py
=> Config linter fixes

tests/cross_agent/fixtures/utilization/utilization_json.json, tests/cross_agent/fixtures/utilization_vendor_specific/gcp.json
Sync cross agent tests with latest changes is cross_agent tests repo.
=> Sync tests w/ agents/cross_agent_tests/pull/150

newrelic/agent.py, newrelic/api/settings.py, newrelic/api/time_trace.py, newrelic/core/config.py, newrelic/core/stats_engine.py, tests/agent_features/test_error_events.py, tests/agent_features/test_error_group_callback.py, tests/testing_support/fixtures.py, tests/testing_support/validators/validate_error_trace_attributes.py
* Add API for error group name callback.
=> Error Group Callback API

newrelic/api/transaction.py, newrelic/config.py, newrelic/core/agent_protocol.py, newrelic/core/application.py, newrelic/core/config.py, newrelic/core/stats_engine.py, newrelic/hooks/mlmodel_sklearn.py, tests/agent_features/test_high_security_mode.py, tests/agent_features/test_ml_events.py, tests/mlmodel_sklearn/test_inference_events.py
Add the following configuration settings for mlops:
* `machine_learning.enabled`
* `machine_learning.inference_events.value.enabled`
* `event_harvest_config.harvest_limits.ml_event_data`
* `ml_insights_events.enabled`
=> Add machine learning and ml_event config options

.github/actions/setup-python-matrix/action.yml, tox.ini
* Add config option which allows the existing tox file to be used on tox v4.
=> Add required option for tox v4

.github/actions/setup-python-matrix/action.yml, .github/workflows/tests.yml, newrelic/config.py, tox.ini
* Restore older CI pipeline until all tests can be fixed.
=> Temporarily Restore Old CI Pipeline

newrelic/common/async_wrapper.py, newrelic/common/coroutine.py, tests/agent_features/_test_async_coroutine_trace.py, tests/agent_features/_test_async_generator_trace.py, tests/agent_features/test_async_generator_trace.py, tests/agent_features/test_coroutine_trace.py
* Add automatic wrapper for async generators.
* Add full test suite for async generator wrapper.
=> Async Generator Wrapper

.devcontainer/Dockerfile
* Fix pyenv installation being owned by root and not unprivileged user in devcontainer.
=> Fix pyenv installation for devcontainer

newrelic/config.py, newrelic/hooks/mlmodel_openai.py, tests/mlmodel_openai/_mock_external_openai_server.py, tests/mlmodel_openai/conftest.py, tests/mlmodel_openai/test_chat_completion_v1.py, tests/mlmodel_openai/test_embeddings_v1.py, tox.ini
Add test infrastructure for openai v1.
=> Add openai v1 test infrastructure

newrelic/hooks/mlmodel_langchain.py, tests/mlmodel_langchain/conftest.py, tests/mlmodel_langchain/test_vectorstore.py
This PR instrumentation and tests for async vectorstore `asimilarity_search` methods
=> Instrumentation for asimilarity_search in Langchain

.github/workflows/deploy-python.yml
=> Add Checkout Action to Deploy Workflow

newrelic/config.py, newrelic/hooks/mlmodel_langchain.py, newrelic/hooks/mlmodel_openai.py, tests/mlmodel_langchain/conftest.py, tests/mlmodel_langchain/test_agent.py, tests/mlmodel_langchain/test_vectorstore.py, tox.ini
Adds instrumentation for agents in Langchain
=> Add langchain agent

newrelic/core/attribute.py, newrelic/hooks/external_botocore.py, newrelic/hooks/mlmodel_openai.py, tests/external_botocore/test_bedrock_chat_completion.py, tests/external_botocore/test_bedrock_embeddings.py, tests/mlmodel_openai/test_chat_completion.py, tests/mlmodel_openai/test_chat_completion_v1.py, tests/mlmodel_openai/test_embeddings.py, tests/mlmodel_openai/test_embeddings_v1.py
This PR adds an `llm: True` attribute to transactions that contain LLM spans.
=> Add LLM attribute to transactions.

tests/agent_features/test_error_events.py, tests/agent_features/test_notice_error.py, tests/testing_support/fixtures.py, tests/testing_support/validators/validate_transaction_error_event_count.py
Move `validate_transaction_error_event_count` from `fixtures.py` into validate directory.
=> Move validate_error_event_count validator

.github/workflows/tests.yml
* Update Kafka images used in CI pipeline.
=> Update Kafka Images on CI

.github/workflows/get-envs.py, tests/logger_logging/test_logging_handler.py, tox.ini
* Remove unsupported cornice version combination from tests.
* Update logging handler tests to correctly handle dicts in Python 2 having no defined item order.
* Add better error message for tox env scripting.
=> Fix Multiple Failing Tests

newrelic/config.py, newrelic/hooks/mlmodel_openai.py, tests/mlmodel_openai/_mock_external_openai_server.py, tests/mlmodel_openai/conftest.py, tests/mlmodel_openai/test_chat_completion_stream_error_v1.py, tests/mlmodel_openai/test_chat_completion_stream_v1.py
Add support for streaming in openai v1
=> Openai stream v1 support

newrelic/config.py, newrelic/core/application.py, newrelic/core/config.py, newrelic/hooks/mlmodel_openai.py, tests/agent_unittests/test_agent_connect.py, tests/mlmodel_openai/conftest.py, tests/mlmodel_openai/test_chat_completion_stream.py, tests/mlmodel_openai/test_chat_completion_stream_v1.py
Add ai_monitoring.streaming.enabled setting.
* `ai_monitoring.streaming.enabled` -- When disabled does not instrument the stream and does not record events.
* Records a supportability metric when streaming is disabled.
=> Add ai_monitoring.streaming.enabled setting

newrelic/api/transaction.py, tests/external_botocore/test_bedrock_chat_completion.py, tests/external_botocore/test_bedrock_embeddings.py, tests/mlmodel_langchain/test_agent.py, tests/mlmodel_langchain/test_chain.py, tests/mlmodel_langchain/test_tool.py, tests/mlmodel_langchain/test_vectorstore.py, tests/mlmodel_openai/test_chat_completion.py, tests/mlmodel_openai/test_chat_completion_stream.py, tests/mlmodel_openai/test_chat_completion_stream_v1.py, tests/mlmodel_openai/test_chat_completion_v1.py, tests/mlmodel_openai/test_embeddings.py, tests/mlmodel_openai/test_embeddings_error.py, tests/mlmodel_openai/test_embeddings_error_v1.py, tests/mlmodel_openai/test_embeddings_v1.py
This PR updates Bedrock, LangChain, and OpenAI framework metrics to supportability metrics for cross-agent consistency.
=> Add ML supportability metrics

newrelic/hooks/external_botocore.py, tests/external_botocore/conftest.py, tests/external_botocore/test_bedrock_chat_completion.py
* Respect streaming disable setting in bedrock streaming support.
=> Bedrock Streaming Disable Setting

.github/workflows/build-ci-image.yml, .github/workflows/deploy-python.yml, .github/workflows/mega-linter.yml, .github/workflows/tests.yml, tox.ini
* Merge main contents into `develop-ai-limited-preview-3`
=> Merge main into develop-ai-limited-preview-3

newrelic/hooks/mlmodel_openai.py
In order to provide a safety-net for our us and our customers, add try-except around fragile parsing code that could cause a crash.
Note this is based on https://github.com/newrelic/newrelic-python-agent/pull/1096 which should be reviewed and merged first.
=> Add try-excepts around fragile openai code

newrelic/hooks/mlmodel_langchain.py, tests/mlmodel_langchain/test_chain.py, tests/mlmodel_langchain/test_tool.py, tests/mlmodel_langchain/test_vectorstore.py
* Fix bug in vectorstore span names and add tests for span names
* Extract shared code into functions.
* Utilize attrs with value of None being dropped.
* Add tests for chain span names.
* Make sure the span is always exited before we record it's duration.
=> Refactor langchain

newrelic/hooks/adapter_asgiref.py, tests/adapter_asgiref/conftest.py, tests/adapter_asgiref/test_context_propagation.py, tox.ini
* Add fix for `asgiref>=3.8.0`
* Add new test suite for asgiref to support testing multiple asgiref versions
=> Fix Asgiref Instrumentation

tests/agent_features/test_priority_sampling.py, tests/agent_streaming/test_infinite_tracing.py, tests/testing_support/util.py
Add a retry decorator and retry `test_no_data_loss_on_reconnect` and `test_priority_used_in_transaction_events` flakey tests.
=> Retry flakey tests

.github/workflows/build-ci-image.yml, .github/workflows/deploy-python.yml, .github/workflows/mega-linter.yml, .github/workflows/tests.yml
* Pin action versions to hashes following security recommendations.
=> Pin All GitHub Actions

newrelic/core/environment.py, tests/mlmodel_sklearn/conftest.py, tests/mlmodel_sklearn/test_cluster_models.py, tests/mlmodel_sklearn/test_dummy_models.py
=> Fix Failing SKLearn Test

.github/workflows/deploy-python.yml
* Change release strategy for deploy flow to not fail fast.
=> Fix Release Strategy

newrelic/hooks/mlmodel_openai.py
Fix a possible typo to make the check against the module function that's actually being wrapped.
N/A
=> fix: openai Embeddings module hasattr typo

newrelic/core/agent_protocol.py, newrelic/core/config.py, tests/agent_unittests/test_agent_protocol.py, tests/agent_unittests/test_connect_response_fields.py
=> Add support for account level AIM disable.

tests/framework_strawberry/_target_schema_async.py, tests/framework_strawberry/_target_schema_sync.py, tox.ini
strawberry v0.236.0 included internal structure changes which requires previous imports to be updated
=> Fix strawberry tests

newrelic/hooks/mlmodel_openai.py
Openai added a new argument which broke our openai instrumentation. In particular it broke our base client arg binding. Change to using auto detection of function signature using bind args.
=> Change to using auto bind on openai base client

newrelic/hooks/datastore_redis.py
Add instrumentation for new redis commands.
=> Add new redis commands

tests/datastore_redis/test_uninstrumented_methods.py, tox.ini
* Bring redis testing matrix back into support window.
* Ignored new method on redis clients in tests.
=> Update Redis Tests for Newer Versions

newrelic/config.py, newrelic/hooks/mlmodel_langchain.py
This PR instruments the SQLiteVec vectorstore in LangChain
=> Instrument SQLiteVec vectorstore in LangChain

tests/mlmodel_sklearn/test_discriminant_analysis_models.py
* Update QuadraticDiscriminantAnalysis expected metrics based on new implementation.
* Relevant implementation changes https://github.com/scikit-learn/scikit-learn/pull/26689/files#diff-088a77600941874d633e8dbe71804c94c3b9d336a73509e6d2db5b48065d1c8b
=> Fix scikit-learn Tests for New Version

newrelic/config.py, newrelic/console.py, newrelic/core/agent.py, newrelic/core/agent_control_health.py, newrelic/core/agent_protocol.py, newrelic/core/application.py, tests/agent_features/test_agent_control_health_check.py, tests/agent_unittests/test_agent_connect.py, tests/testing_support/http_client_recorder.py
This PR refactors the health check code to use the name Agent Control instead of Super Agent
=> Refactor super agent to agent control.

tests/mlmodel_langchain/conftest.py, tests/mlmodel_langchain/test_chain.py
* Fix langchain tests by adding an explicit temperature and document ID setting.
=> Fix Langchain Tests

.github/workflows/deploy-python.yml
Add quotes around title and notes.
=> Add quotes to release tags workflow

.github/workflows/deploy-python.yml
* Update versions for `qemu` and `cibuildwheel`
=> Update Deploy Action Versions

tests/mlmodel_langchain/test_vectorstore.py
* Fix tests related to new metadata on langchain vectorestore events.
=> Fix Langchain PDF Vectorstore Tests

.github/workflows/deploy-python.yml, setup.py
Pins the setuptools version to v75.8.1 for now.
=> Pin setuptools_scm (for now)

.github/workflows/deploy-python.yml
=> Add packaging to install.

.github/containers/Dockerfile, .github/containers/requirements-tox.txt, .github/containers/requirements.txt, MANIFEST.in, tox.ini
* Pin `virtualenv` and `pip` for Python 3.7 compatibility.
* Completed CI run with dev CI image https://github.com/newrelic/newrelic-python-agent/actions/runs/14068421028/job/39397228140?pr=1332
=> Fix Broken CI

setup.py
* Add content type for README file to fix parsing on PyPi.
=> Fix Description Type for PyPi

.github/workflows/tests.yml, .github/workflows/trivy.yml
Move Trivy to it's own workflow.
=> Move trivy to separate workflow

newrelic/config.py, tox.ini
Comment out Kombu instrumentation & tests until we can determine and fix root cause of producer crash.
=> Comment out Kombu instrumentation & tests

.github/workflows/tests.yml
* Fix find and replace artifact from updating versions of github actions.
=> Fix Comment in GHA Workflow

newrelic/hooks/external_botocore.py
This PR instruments the following new Kinesis methods:
- `untag_resource`
- `tag_resource`
- `list_tags_for_resource`
=> Instrument new Kinesis methods.

README.md
* Fix leftover RST artifact in README to be markdown.
=> Fix README RST Artifact

tests/datastore_redis/test_asyncio.py, tests/datastore_valkey/test_asyncio.py
* Fix flakey test_async_pubsub test in both Redis and Valkey tests (which is a clone of the Redis tests).
=> Fix Flakey test_async_pubsub in Redis Tests

newrelic/config.py, newrelic/hooks/adapter_mcp.py, tests/adapter_mcp/conftest.py, tests/adapter_mcp/test_tools.py, tox.ini
This PR adds instrumentation to trace tool calls made within MCP.
=> Add MCP tool instrumentation

README.md
Replaces dead license key link in README with new link.
=> Fix dead license key link
